/**
 * EcoSwapSVM solver reference — the TS mirror of the QUANTIZED on-chain
 * solver (codegen.ts), transcribed bit-for-bit: the same geometric grid, the
 * same rung construction, the same k-way cheapest-rung-first merge with the
 * same candidate scan order, cross-multiplied price compare, clamp and
 * pointer advance, in the same integer ops and truncation order. This is THE
 * lamport-exact gate target for the engine-executed bytecode AND the
 * user-facing quote (quoteEcoSwapSvm evaluates it over fetched account
 * bytes — no simulation, no chain-side execution).
 *
 * The only inputs are per-slot exact quote closures (the ladder adapters'
 * referenceQuote over the SAME live account bytes the fragment reads) and
 * the trade amount, so the mirror is family-agnostic — venue math lives in
 * one place per family (the adapter) on each side of the mirror.
 *
 * Every quote closure is nondecreasing in x with quote(0) == 0 (the adapter
 * contract), so rung dOut values are non-negative and all products stay far
 * below 2^256 for u64 amounts — plain bigint arithmetic matches the engine's
 * wrapping ops exactly on this domain.
 */

/** Rungs per slot ladder — fixed for the Phase 0 shape (see README, honest limits). */
export const QL_S = 4;

export interface LadderRung {
  /** Gross-input capacity of this rung (may be 0 for dust grid points). */
  dIn: bigint;
  /** Venue output produced across the rung — the merge price is dOut/dIn. */
  dOut: bigint;
}

export interface SolverSlotInput {
  /** Exact integer venue quote for gross input x over the live account bytes. */
  quote: (x: bigint) => bigint;
  /** Disabled slots are born exhausted (never quoted, never filled). */
  enabled?: boolean;
}

export interface SolverReferenceResult {
  /** Per-slot gross-input slices; sums to amountIn exactly. */
  slices: bigint[];
  /** Per-slot predicted outputs: quote(slice). */
  predictedOuts: bigint[];
  /** Sum of predicted outputs — what the pre-CPI minOut check sees. */
  totalPredicted: bigint;
}

/**
 * The per-slot geometric ladder: cumulative grid points G_j = amountIn >>
 * (QL_S − j) for j = 1..QL_S (so G_QL_S == amountIn — one slot can always
 * absorb the whole trade), rung j spanning (G_{j−1}, G_j] with dOut =
 * quote(G_j) − quote(G_{j−1}). Fine rungs near zero, coarse near the full
 * amount: the merge's partial-fill of the marginal rung recovers exact
 * resolution at the cut for the slot that binds there.
 */
export function buildLadder(quote: (x: bigint) => bigint, amountIn: bigint): LadderRung[] {
  const rungs: LadderRung[] = [];
  let gPrev = 0n;
  let oPrev = 0n;
  for (let j = 1; j <= QL_S; j++) {
    const g = amountIn >> BigInt(QL_S - j);
    const o = quote(g);
    rungs.push({ dIn: g - gPrev, dOut: o - oPrev });
    gPrev = g;
    oPrev = o;
  }
  return rungs;
}

/**
 * The quantized water-fill: greedy cheapest-rung-first k-way merge over the
 * per-slot ladders. Each step elects the best next rung by average execution
 * price (cross-multiplied, integer-exact: dOut_c·dIn_b > dOut_b·dIn_c;
 * ties keep the earliest-scanned slot, so slot order encodes preference),
 * consumes it up to the remaining amount, and advances only that slot's
 * pointer. Transcribes the generated bytecode's merge loop 1:1 — do not
 * "optimize" either side independently.
 */
export function solveReference(slots: readonly SolverSlotInput[], amountIn: bigint): SolverReferenceResult {
  const k = slots.length;
  if (k === 0) throw new Error('solveReference needs at least one slot');
  if (amountIn <= 0n) throw new Error(`solveReference amountIn must be positive, got ${amountIn}`);

  const din: bigint[] = new Array(k * QL_S).fill(0n);
  const dout: bigint[] = new Array(k * QL_S).fill(0n);
  const ptr: number[] = new Array(k).fill(0);
  const fill: bigint[] = new Array(k).fill(0n);

  slots.forEach((slot, i) => {
    if (slot.enabled === false) {
      ptr[i] = QL_S; // born exhausted, mirroring the in-VM enable gate
      return;
    }
    buildLadder(slot.quote, amountIn).forEach((rung, j) => {
      din[i * QL_S + j] = rung.dIn;
      dout[i * QL_S + j] = rung.dOut;
    });
  });

  let remaining = amountIn;
  for (let it = 0; it < k * QL_S && remaining > 0n; it++) {
    let best = k;
    for (let s = 0; s < k; s++) {
      if (ptr[s] < QL_S) {
        if (best === k) best = s;
        if (best !== s) {
          const c = s * QL_S + ptr[s];
          const b = best * QL_S + ptr[best];
          if (dout[c] * din[b] > dout[b] * din[c]) best = s;
        }
      }
    }
    if (best === k) throw new Error('solveReference: no enabled capacity left (mirrors the on-chain "fill" revert)');
    const r = best * QL_S + ptr[best];
    let take = din[r];
    if (take > remaining) take = remaining;
    fill[best] += take;
    remaining -= take;
    if (take === din[r]) ptr[best] += 1;
  }
  if (remaining > 0n) throw new Error('solveReference: amountIn not fully assigned (mirrors the on-chain "fill" revert)');

  const predictedOuts = slots.map((slot, i) => (slot.enabled === false ? 0n : slot.quote(fill[i])));
  return {
    slices: fill,
    predictedOuts,
    totalPredicted: predictedOuts.reduce((sum, out) => sum + out, 0n),
  };
}
