/**
 * Consumer-union barrel-surface check -- the omission-catching counterpart to
 * migrated-barrel-surface.test.ts (see that file's header for the full
 * distinction). That sibling test asserts the barrel's OWN emitted name list
 * against itself -- it re-derives its names by reading the very
 * `venues/index.ts` lines it is meant to guard, so a name no one thought to
 * export at all is invisible to it by construction. This is exactly how
 * `SvmHyloDriftError`'s earlier absence from the barrel survived it unnoticed.
 *
 * This test instead asserts against an INDEPENDENTLY-SOURCED list: every
 * symbol name the downstream `sauce-recipes` package actually consumes,
 * extracted mechanically from ITS source tree, not from anything in this
 * repo. A name omitted here fails in the SDK, at PR time -- not one repo
 * away, after a re-pin.
 *
 * DERIVATION. In the `sauce-recipes` repo, over its SVM recipe code,
 * `solswap/**` and `test/svm/**`: the union of every named import sourced
 * from `'@eco-incorp/sauce-sdk/svm'`. RE-DERIVED after that package took over
 * the eco-swap merge-decomposition LADDERS: it now defines every `*Ladder`,
 * every window selector and every rung-feeding decomposition helper locally
 * (its own `ladders/*.ts`), and imports from this barrel only the GENERIC
 * venue integration -- pool-account adapters, program ids / registry
 * addresses / mint constants, pool-config types, and the AMM/tick math the
 * adapters need. Every ladder name that used to appear in this list is gone
 * from it because the SDK no longer exports one, and the consumer no longer
 * asks for one.
 *
 * 547 names total: 445 VALUES (below) + 102 TYPES
 * (consumer-union-types.fixture.ts).
 *
 * VALUES are probed as runtime values against the built module namespace --
 * the exact thing a real `import { X } from '@eco-incorp/sauce-sdk/svm'`
 * needs. TYPES have no runtime presence and this package's `jest.config.cjs`
 * runs ts-jest with `diagnostics: false`, so a bare `import type { Foo }`
 * that names a missing export is SILENTLY ERASED at transpile time and would
 * never fail a jest run by itself -- to make the type half load-bearing, the
 * third test below drives the TypeScript compiler API directly (in-process,
 * not a subprocess) against `consumer-union-types.fixture.ts`, a file whose
 * only job is to import every listed type and reference each in one tuple
 * position, and asserts zero diagnostics.
 *
 * One consumer name is deliberately NOT in either list: `SvmVenueLadderV2`,
 * which the 0.5.0 branding change renamed to `SvmVenueLadder` (carried here
 * under the new name). That rename predates the ladder relocation and is
 * unrelated to it.
 */
import * as svm from '../../../src/svm/index.js';
import ts from 'typescript';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

const CONSUMER_UNION_VALUES: readonly string[] = [
  'ALDRIN_V1_PROGRAM_ID',
  'ALDRIN_V2_PROGRAM_ID',
  'ALPHAQ_PROGRAM_ID',
  'BIDS_NODES_BASE',
  'BIN_LEN',
  'BONKSWAP_PROGRAM_AUTHORITY',
  'BONKSWAP_PROGRAM_ID',
  'BONKSWAP_STATE',
  'BUY_DISCRIMINATOR',
  'BYREAL_PROGRAM_ID',
  'CARROT_MAX_ASSETS',
  'CARROT_PROGRAM_ID',
  'CARROT_TOKEN_2022_MINTS',
  'CARROT_VAULT_ADDRESS',
  'CENTER_PRICE_SCALE',
  'CFG',
  'CREMA_OFF_FEE_RATE',
  'CREMA_OFF_LIQUIDITY',
  'CREMA_OFF_SQRT_PRICE',
  'CREMA_OFF_TA_TICKS',
  'CREMA_OFF_TICK_CURRENT',
  'CREMA_PROGRAM_ID',
  'CREMA_TICK_LEN',
  'CROPPER_MAX_SQRT_PRICE',
  'CROPPER_MIN_SQRT_PRICE',
  'CROPPER_PROGRAM_ID',
  'CRT_MINT',
  'DEFITUNA_PROGRAM_ID',
  'DELEGATE_NO_INIT_DISCRIMINATOR',
  'DERIVERSE_PROGRAM_ID',
  'DEXLAB_PROGRAM_ID',
  'DOVES_PRICE_OFFSET',
  'EXPIRY_SCALE',
  'FEE_DENOMINATOR',
  'FEE_SCALE',
  'FINALIZE_BUFFER_DISCRIMINATOR',
  'FLAT_SLAB_PROGRAM_ID',
  'FLUXBEAM_PROGRAM_ID',
  'GAMMA_PROGRAM_ID',
  'GAVEL_LEADER_SLOT_WINDOW',
  'GAVEL_PROGRAM_ID',
  'GOONFI_ASSUMED_DENOM',
  'GOONFI_SWAP_TAG',
  'GOONFI_V2_PROGRAM_ID',
  'GUACSWAP_PROGRAM_AUTHORITY',
  'GUACSWAP_PROGRAM_ID',
  'GUACSWAP_STATE',
  'HEAVEN_PROGRAM_ID',
  'HUMA_PROGRAM_ID',
  'HUMIDIFI_AMOUNT_XOR_MASK',
  'HUMIDIFI_POOL_REGISTRY',
  'HUMIDIFI_PROGRAM_ID',
  'HUMIDIFI_SAFETY_FEE_PPM',
  'HYLO_ACCOUNT',
  'HYLO_PROGRAM_ID',
  'HYLO_STABILITY_POOL_CONFIG',
  'HYLO_STABILITY_POOL_LP_TOKEN_MINT',
  'HYLO_STABILITY_POOL_PROGRAM_ID',
  'HYLO_STABILITY_POOL_STABLECOIN_MINT',
  'HYUSD_MINT',
  'INIT_BUFFER_DISCRIMINATOR',
  'INSTRUCTIONS_SYSVAR',
  'INVARIANT_PROGRAM_ID',
  'JUPITER_LEND_EARN_PROGRAM_ID',
  'JUPITER_LEND_LIQUIDITY_PROGRAM_ID',
  'JUPLEND_AMM_PROGRAM_ID',
  'JUPLEND_SWAP_IN_DISCRIMINATOR',
  'LST_STATE_LIST_ID',
  'MANIFEST_PROGRAM_ID',
  'MARKET_FIXED_SIZE',
  'MASK_SUSPENDED',
  'MAX_SQRT_PRICE_X64',
  'MERCURIAL_PROGRAM_ID',
  'METADAO_FUTARCHY_EVENT_AUTHORITY',
  'METADAO_FUTARCHY_PROGRAM_ID',
  'METEORA_DBC_CURVE_POINT_SIZE',
  'METEORA_DBC_EVENT_AUTHORITY',
  'METEORA_DBC_FEE_DENOMINATOR',
  'METEORA_DBC_MAX_FEE_NUMERATOR',
  'METEORA_DBC_OFF_ACTIVATION_POINT',
  'METEORA_DBC_OFF_CLIFF_FEE_NUMERATOR',
  'METEORA_DBC_OFF_COLLECT_FEE_MODE',
  'METEORA_DBC_OFF_CURVE',
  'METEORA_DBC_OFF_DYN_BIN_STEP',
  'METEORA_DBC_OFF_DYN_INITIALIZED',
  'METEORA_DBC_OFF_DYN_VARIABLE_FEE_CONTROL',
  'METEORA_DBC_OFF_MIGRATION_SQRT_PRICE',
  'METEORA_DBC_OFF_NUMBER_OF_PERIOD',
  'METEORA_DBC_OFF_PERIOD_FREQUENCY',
  'METEORA_DBC_OFF_REDUCTION_FACTOR',
  'METEORA_DBC_OFF_SQRT_PRICE',
  'METEORA_DBC_OFF_SQRT_START_PRICE',
  'METEORA_DBC_OFF_VOL_ACCUMULATOR',
  'METEORA_DBC_POOL_AUTHORITY',
  'METEORA_DBC_SWAP_DISCRIMINATOR',
  'METEORA_DLMM_PROGRAM_ID',
  'MID_SCALE',
  'MINT_SUPPLY_OFFSET',
  'MIN_SQRT_PRICE_X64',
  'MOONIT_PROGRAM_ID',
  'MSWAP_PROGRAM_ID',
  'M_MINT',
  'M_TOKEN_PROGRAM',
  'OBRIC_SWAP_DISCRIMINATOR',
  'OBRIC_V2_PROGRAM_ID',
  'OFF_ACTIVE_ID',
  'OFF_ASSET_TOKENS',
  'OFF_BA_BINS',
  'OFF_BIN_RESERVE_X',
  'OFF_BIN_RESERVE_Y',
  'OFF_CACHED_TS',
  'OFF_CENTER_PRICE',
  'OFF_CFG_TRADE_FEE_RATE',
  'OFF_CRNCY_TOKENS',
  'OFF_DECAY_PPM',
  'OFF_DEC_FACTOR',
  'OFF_FEE_RATE',
  'OFF_FEE_SCALE',
  'OFF_INDEX_REF',
  'OFF_LAST_PX',
  'OFF_LAST_SWAP_SLOT',
  'OFF_LAST_UPDATE',
  'OFF_LIQUIDITY',
  'OFF_MASK',
  'OFF_MID',
  'OFF_MINT_A',
  'OFF_MINT_B',
  'OFF_MULT_X',
  'OFF_MULT_Y',
  'OFF_ORACLE_DENOM',
  'OFF_ORACLE_P1',
  'OFF_ORACLE_P2',
  'OFF_ORACLE_PRICE',
  'OFF_ORACLE_SPREAD',
  'OFF_ORACLE_UPDATED_AT',
  'OFF_ORDER_PRICE',
  'OFF_ORDER_SEQ',
  'OFF_ORDER_SIZE',
  'OFF_POOL_RESERVE',
  'OFF_POSITION_AMOUNT',
  'OFF_POSITION_CEILING',
  'OFF_PYTH_PRICE',
  'OFF_PYTH_PUBLISH_TIME',
  'OFF_PYTH_VERIFICATION_TAG',
  'OFF_SKEW_DEN',
  'OFF_SKEW_HI',
  'OFF_SKEW_LO_MAG',
  'OFF_SKEW_NUM',
  'OFF_SPLINE_AGE',
  'OFF_SPLINE_D0',
  'OFF_SPLINE_D1',
  'OFF_SPLINE_SF',
  'OFF_SPREAD_DIR0',
  'OFF_SPREAD_DIR1',
  'OFF_SQRT_PRICE',
  'OFF_TAKER_FEE_BPS',
  'OFF_TA_TICKS',
  'OFF_THRESHOLD',
  'OFF_TICK_CURRENT',
  'OFF_TICK_LIQ_GROSS',
  'OFF_TICK_LIQ_NET',
  'OFF_TOKEN_X_RESERVE',
  'OFF_TOKEN_Y_RESERVE',
  'OFF_VOLATILITY_ACC',
  'OFF_VOLATILITY_REF',
  'OMNIPAIR_PROGRAM_ID',
  'ONE_E18',
  'ONE_E5',
  'OPENBOOK_V2_PROGRAM_ID',
  'ORACLE_KEY_WORDS',
  'ORACLE_OFF_CONF',
  'ORACLE_OFF_EXP',
  'ORACLE_OFF_EXPIRY_SLOT',
  'ORACLE_OFF_FEE_WORD',
  'ORACLE_OFF_MAN',
  'ORACLE_OFF_SLOT',
  'ORACLE_OFF_TS',
  'ORACLE_PRICE_SCALE',
  'ORCA_MINT_ID',
  'ORCA_V1_PROGRAM_ID',
  'ORCA_WHIRLPOOL_PROGRAM_ID',
  'PANCAKESWAP_CLMM_OFF_LIQUIDITY',
  'PANCAKESWAP_CLMM_OFF_SQRT_PRICE',
  'PANCAKESWAP_CLMM_OFF_TA_TICKS',
  'PANCAKESWAP_CLMM_OFF_TICK_CURRENT',
  'PANCAKESWAP_CLMM_PROGRAM_ID',
  'PANCAKESWAP_CLMM_TICK_LEN',
  'PENGUIN_PROGRAM_ID',
  'PERENA_PROGRAM_ID',
  'PERENA_STAR_PROGRAM_ID',
  'PERPS_JLP_PROGRAM_ID',
  'PHOENIX_PROGRAM_ID',
  'POOL_STATE_ID',
  'PRICE_D18',
  'PRICE_PPM_DEN',
  'PUMPFUN_BONDING_CURVE_ASSOCIATED_USER_VOLUME_ACCUMULATOR_REF',
  'PUMPFUN_BONDING_CURVE_PROGRAM_ID',
  'PUMPFUN_BONDING_CURVE_USER_VOLUME_ACCUMULATOR_REF',
  'PUMPSWAP_PROGRAM_ID',
  'PYTH_VERIFICATION_FULL',
  'QUANTUM_KIND_TRAPEZOID',
  'QUANTUM_PROGRAM_ID',
  'RAYDIUM_CLMM_PROGRAM_ID',
  'RAYDIUM_LAUNCHLAB_PROGRAM_ID',
  'SABER_STABLESWAP_PROGRAM_ID',
  'SANCTUM_INFINITY_PROGRAM_ID',
  'SANCTUM_STAKE_POOL_2_PROGRAM_ID',
  'SANCTUM_STAKE_POOL_3_PROGRAM_ID',
  'SANCTUM_STAKE_POOL_4_PROGRAM_ID',
  'SANCTUM_STAKE_POOL_PROGRAM_ID',
  'SAROS_DLMM_MEMO_PROGRAM',
  'SAROS_DLMM_PROGRAM_ID',
  'SAROS_PROGRAM_ID',
  'SCALE_AMM_PROGRAM_ID',
  'SCALE_CURVE_HELPER_NAME',
  'SCALE_CURVE_HELPER_SOURCE',
  'SCALE_VMM_PROGRAM_ID',
  'SCORCH_CORE_PROGRAM_ID',
  'SCORCH_HAIRCUT_PPM',
  'SCORCH_ROUTER_PROGRAM_ID',
  'SELL_DISCRIMINATOR',
  'SIDE_EXPIRY',
  'SIDE_KINDS',
  'SIDE_LEVELS',
  'SIDE_LEVEL_STRIDE',
  'SLAB_ID',
  'SOLAYER_PROGRAM_ID',
  'SOLFI_V1_PROGRAM_ID',
  'SOLFI_V2_PROGRAM_ID',
  'SPLINE_LEN_STRIDE',
  'SPLINE_X_STRIDE',
  'SPLINE_Y_STRIDE',
  'SPL_TOKEN_PROGRAM_ID',
  'STABBLE_CLMM_OFF_CFG_TRADE_FEE_RATE',
  'STABBLE_CLMM_OFF_LIQUIDITY',
  'STABBLE_CLMM_OFF_SQRT_PRICE',
  'STABBLE_CLMM_OFF_TA_TICKS',
  'STABBLE_CLMM_OFF_TICK_CURRENT',
  'STABBLE_CLMM_OFF_TICK_LIQ_GROSS',
  'STABBLE_CLMM_OFF_TICK_LIQ_NET',
  'STABBLE_CLMM_PROGRAM_ID',
  'STABBLE_CLMM_TICK_LEN',
  'STABBLE_SWAP_DISCRIMINATOR',
  'STABBLE_TOKEN_PROGRAM_ID',
  'STABBLE_VAULT_PROGRAM_ID',
  'STATE_ESCROWED_OFFSET',
  'STEPN_PROGRAM_ID',
  'SWAP2_DISCRIMINATOR',
  'SWAP_GLOBAL_ID',
  'SWAP_M_ACCOUNT',
  'SYSTEM_PROGRAM',
  'SvmHyloDriftError',
  'TESSERAV_PROGRAM_ID',
  'TICK_DISCRIMINATOR',
  'TICK_LEN',
  'TOKEN_PROGRAM',
  'TOKEN_SWAP_V1_PROGRAM_ID',
  'TRENDS_CONFIG_PDA',
  'TRENDS_EVENT_AUTHORITY',
  'TRENDS_POOL_AUTHORITY',
  'TRENDS_PROGRAM_ID',
  'TRENDS_WSOL_MINT',
  'UNDELEGATE_NO_INIT_DISCRIMINATOR',
  'USDC_COLLATERAL_VAULT',
  'USDC_MINT',
  'USDC_PAIR_ACCOUNT',
  'USDC_USD_PYTH_FEED',
  'USER_VOLUME_ACCUMULATOR_REF',
  'VAULT_AMOUNT_OFFSET',
  'VIRTUALS_MINT',
  'VIRTUALS_PROGRAM_ID',
  'VOLTR_PROGRAM_ID',
  'WEIGHTED_MAX_IN_RATIO',
  'WOOFI_PROGRAM_ID',
  'WOOFI_SWAP_DISCRIMINATOR',
  'WRITE_BUFFER_DISCRIMINATOR',
  'WSOL_CALC_PROGRAM_ID',
  'WSOL_MINT',
  'XORCA_MINT_ID',
  'XORCA_PROGRAM_ID',
  'XORCA_STATE_PDA',
  'XORCA_VAULT_ATA',
  '__decodeMeteoraDbcConfig',
  '__decodeMeteoraDbcPool',
  'aldrin',
  'aldrinV2',
  'bakedDecimalScale',
  'bonkswap',
  'bonkswapForkConfig',
  'bonkswapReadUintLE',
  'buildAtaPrepend',
  'buildCloseBufferInstruction',
  'buildExecuteFromAccountInstruction',
  'buildFinalizeBufferInstruction',
  'buildHeapFramePrepend',
  'buildInitBufferInstructions',
  'buildStagingPlan',
  'buildWriteBufferInstruction',
  'byreal',
  'calcUnwrappedAmount',
  'calcWrappedAmount',
  'carrot',
  'carrotAllDirections',
  'ceilDiv',
  'coalescingAccountLoader',
  'complement',
  'computeScaleQuote',
  'crema',
  'cropper',
  'dbcCapacity',
  'dbcFeeNumerator',
  'defituna',
  'denomAdjustedFor',
  'depthReserves',
  'deriveBufferPda',
  'deriverse',
  'deriverseSwapAccounts',
  'dexlab',
  'dlmmAmountIn',
  'dlmmAmountOut',
  'dlmmPriceFromId',
  'encodePayloadArgs',
  'eventAuthorityPda',
  'fetchAlphaqPoolConfig',
  'fetchHumidifiConfig',
  'fetchMetaDaoFutarchySpotConfig',
  'fetchOpenBookV2Config',
  'fetchSolfiV1Config',
  'fetchVoltrConfig',
  'fetchXorcaConfig',
  'fluxbeam',
  'gamma',
  'gavel',
  'goonfiSwapAccounts',
  'goonfiV2',
  'guacswap',
  'heaven',
  'huma',
  'humaDepositAccounts',
  'humaEncodeDepositData',
  'humaEncodeInstantWithdrawData',
  'humaFeeAssignLines',
  'humaFeeBpsFor',
  'humaInstantWithdrawAccounts',
  'humidifiKeystream',
  'hylo',
  'hyloGate',
  'hyloMintOut',
  'hyloRedeemCapacity',
  'hyloRedeemOut',
  'hyloStabilityPool',
  'invariant',
  'invariantComputeSwapStepIn',
  'jupiterLendEarn',
  'juplendAmm',
  'juplendAmmSwapAccounts',
  'level0CumOffset',
  'level0PriceOffset',
  'manifest',
  'mercurial',
  'metadaoFutarchySpotQuote',
  'meteoraDammV1Stable',
  'meteoraDammV2',
  'meteoraDbc',
  'meteoraDlmm',
  'moonit',
  'mswap',
  'mswapPoolKey',
  'mulDown',
  'obricV2',
  'omnipair',
  'omnipairCapacity',
  'omnipairQuote',
  'orcaLegacyTokenSwap',
  'orcaV1',
  'orcaWhirlpool',
  'pancakeswapClmm',
  'parseCarrotDirection',
  'penguin',
  'perena',
  'perenaStar',
  'perenaSwapOut',
  'perpetualsPda',
  'perpsJlp',
  'perpsJlpConfig',
  'phoenix',
  'priceFromId',
  'pumpfunBondingCurve',
  'pumpswapAdapter',
  'quantum',
  'quantumInVault',
  'quantumOutReserveOffset',
  'quantumOutScale',
  'quantumOutVault',
  'quantumSideBase',
  'quoteSingleSegment',
  'raydiumAmmV4',
  'raydiumClmm',
  'raydiumCpSwap',
  'raydiumLaunchlab',
  'raydiumSqrtPriceAtTick',
  'readUintLE',
  'referenceCapacities',
  'referenceQuote',
  'resolveAccounts',
  'saberStableswap',
  'sanctumInfinity',
  'sanctumInfinityPoolKey',
  'sanctumStakePool',
  'sanctumStakePool2',
  'sanctumStakePool3',
  'sanctumStakePool4',
  'saros',
  'sarosDlmm',
  'scaleAmm',
  'scaleCommonReadUintLE',
  'scaleContinuousFees',
  'scaleDepthReserves',
  'scaleVmm',
  'scorch',
  'selectAltAddresses',
  'solayer',
  'solfiSwapAccounts',
  'solfiV2',
  'stabbleClmm',
  'stabbleStableSwap',
  'stabbleWeightedSwap',
  'stableCalcInvariantN',
  'stableDHelperSource',
  'stableGetAmplification',
  'stableGetBalanceGivenInvariantWarm',
  'stableYWarmHelperSource',
  'stepn',
  'swapAccounts',
  'tesserav',
  'tokenSwapV1',
  'transferAuthorityPda',
  'trends',
  'vaultLiquidUnstake',
  'vaultLiquidUnstakeQuote',
  'virtuals',
  'weightedCalcOutGivenIn',
  'weightedCoreQuoteLines',
  'woofi',
  'woofiSwapAccounts',
];

const CONSUMER_UNION_TYPES: readonly string[] = [
  'AccountBytesMap',
  'AccountLoader',
  'AccountResolution',
  'AldrinPoolConfig',
  'AlphaqPoolConfig',
  'BatchAccountLoader',
  'BonkswapForkPoolConfig',
  'ByrealPoolConfig',
  'CarrotAssetSnapshot',
  'CarrotPoolConfig',
  'CremaPoolConfig',
  'CremaWindow',
  'CropperPoolConfig',
  'CropperWindow',
  'DefiTunaPoolConfig',
  'DefiTunaWindow',
  'DeriversePoolConfig',
  'DlmmWindow',
  'EnsuredLookupTable',
  'FluxBeamPoolConfig',
  'GammaPoolConfig',
  'GavelPoolConfig',
  'GoonfiV2PoolConfig',
  'HeavenPoolConfig',
  'HumaPoolConfig',
  'HumidiFiPoolConfig',
  'HyloPoolConfig',
  'HyloStabilityPoolConfig',
  'HyloStabilityPoolDirection',
  'InvariantPoolConfig',
  'InvariantWindow',
  'JupiterLendEarnPoolConfig',
  'JuplendAmmPoolConfig',
  'LadderSwapTemplate',
  'LoadedAccount',
  'MSwapPoolConfig',
  'ManifestPoolConfig',
  'ManifestWindow',
  'MercurialPoolConfig',
  'MetaDaoFutarchySpotPoolConfig',
  'MeteoraDammV1StablePoolConfig',
  'MeteoraDammV2PoolConfig',
  'MeteoraDbcPoolConfig',
  'MeteoraDlmmPoolConfig',
  'MoonitPoolConfig',
  'ObricV2PoolConfig',
  'OmnipairPoolConfig',
  'OpenBookV2PoolConfig',
  'OpenBookV2Window',
  'OrcaLegacyPoolConfig',
  'OrcaWhirlpoolPoolConfig',
  'PancakeswapClmmPoolConfig',
  'PancakeswapClmmWindow',
  'PerenaLiveState',
  'PerenaPoolConfig',
  'PerenaStarPoolConfig',
  'PerpsJlpPoolConfig',
  'PhoenixPoolConfig',
  'PhoenixWindow',
  'PoolConfig',
  'PumpfunBondingCurvePoolConfig',
  'PumpswapPoolConfig',
  'QuantumPoolConfig',
  'QuantumWindow',
  'RaydiumAmmV4PoolConfig',
  'RaydiumClmmPoolConfig',
  'RaydiumClmmWindow',
  'RaydiumCpSwapPoolConfig',
  'RaydiumLaunchlabPoolConfig',
  'SaberPoolConfig',
  'SanctumInfinityLegConfig',
  'SanctumInfinityPoolConfig',
  'SanctumStakePoolConfig',
  'SarosDlmmPoolConfig',
  'SarosDlmmWindow',
  'SauceSvmClient',
  'ScaleAmmPoolConfig',
  'ScaleCurveState',
  'ScaleDirection',
  'ScaleVmmPoolConfig',
  'ScorchPoolConfig',
  'SendExecuteResult',
  'SolayerPoolConfig',
  'SolfiV1PoolConfig',
  'SolfiV2PoolConfig',
  'SplTokenSwapForkPoolConfig',
  'StabbleClmmPoolConfig',
  'StabbleClmmWindow',
  'StabbleStableSwapPoolConfig',
  'StabbleWeightedSwapPoolConfig',
  'StagedBuffer',
  'SvmVenueLadder',
  'SwapUser',
  'TesseraVPoolConfig',
  'TrendsPoolConfig',
  'VaultLiquidUnstakePoolConfig',
  'VenueAccount',
  'VirtualsPoolConfig',
  'VoltrPoolConfig',
  'WhirlpoolWindow',
  'WoofiPoolConfig',
  'XorcaPoolConfig',
];

describe('consumer-union barrel surface (sauce-recipes)', () => {
  it('pins the expected counts (445 values, 102 types) so a future edit is deliberate', () => {
    expect(CONSUMER_UNION_VALUES.length).toBe(445);
    expect(CONSUMER_UNION_TYPES.length).toBe(102);
  });

  it('every consumer-union VALUE resolves through the built @eco-incorp/sauce-sdk/svm barrel', () => {
    const missing = CONSUMER_UNION_VALUES.filter((name) => (svm as Record<string, unknown>)[name] === undefined);
    expect(missing).toEqual([]);
  });

  it('every consumer-union TYPE resolves -- checked via the TypeScript compiler API against the fixture', () => {
    const fixturePath = join(HERE, 'consumer-union-types.fixture.ts');
    const program = ts.createProgram([fixturePath], {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.ESNext,
      moduleResolution: ts.ModuleResolutionKind.Bundler,
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      noEmit: true,
    });
    const diagnostics = ts
      .getPreEmitDiagnostics(program)
      .filter((d) => d.file?.fileName === fixturePath)
      .map((d) => ts.flattenDiagnosticMessageText(d.messageText, '\n'));
    expect(diagnostics).toEqual([]);
  });

  it('sanity: every CONSUMER_UNION_TYPES name is absent from CONSUMER_UNION_VALUES (no double-classification)', () => {
    const valueSet = new Set(CONSUMER_UNION_VALUES);
    const overlap = CONSUMER_UNION_TYPES.filter((name) => valueSet.has(name));
    expect(overlap).toEqual([]);
  });
});
