/**
 * Type-only half of the consumer-union barrel-surface check
 * (consumer-union-surface.test.ts). This file is NEVER imported at runtime —
 * it exists solely so `ts.createProgram` (invoked from that test, in-process,
 * not a subprocess) has a real compilation unit to type-check. A type import
 * is erased by ts-jest before the test body ever runs (this package's
 * jest.config.cjs sets `diagnostics: false`), so a plain `import type { Foo }`
 * inside the test file itself would silently no-op on a missing `Foo` — this
 * fixture plus the explicit compiler-API check is what makes the type half of
 * the union load-bearing rather than decorative.
 *
 * The list below is every TYPE name sauce-recipes' `the consuming app SVM code**`,
 * `solswap/**`, and `test/svm/**` need from `@eco-incorp/sauce-sdk/svm` — see
 * consumer-union-surface.test.ts's header for the full derivation.
 */
import type {
  AccountBytesMap,
  AccountLoader,
  AccountResolution,
  AldrinPoolConfig,
  AlphaqPoolConfig,
  BatchAccountLoader,
  BonkswapForkPoolConfig,
  ByrealPoolConfig,
  CarrotPoolConfig,
  CremaPoolConfig,
  CropperPoolConfig,
  DefiTunaPoolConfig,
  DeriversePoolConfig,
  EnsuredLookupTable,
  FluxBeamPoolConfig,
  GammaPoolConfig,
  GavelPoolConfig,
  GoonfiV2PoolConfig,
  HeavenPoolConfig,
  HumidiFiPoolConfig,
  HyloPoolConfig,
  HyloStabilityPoolConfig,
  HyloStabilityPoolDirection,
  InvariantPoolConfig,
  JupiterLendEarnPoolConfig,
  LadderSwapTemplate,
  LoadedAccount,
  MSwapPoolConfig,
  ManifestPoolConfig,
  MercurialPoolConfig,
  MetaDaoFutarchySpotPoolConfig,
  MeteoraDammV1StablePoolConfig,
  MeteoraDammV2PoolConfig,
  MeteoraDbcPoolConfig,
  MeteoraDlmmPoolConfig,
  MoonitPoolConfig,
  ObricV2PoolConfig,
  OmnipairPoolConfig,
  OpenBookV2PoolConfig,
  OrcaLegacyPoolConfig,
  OrcaWhirlpoolPoolConfig,
  PancakeswapClmmPoolConfig,
  PerenaPoolConfig,
  PerenaStarPoolConfig,
  PerpsJlpPoolConfig,
  PhoenixPoolConfig,
  PoolConfig,
  PumpfunBondingCurvePoolConfig,
  PumpswapPoolConfig,
  QuantumPoolConfig,
  RaydiumAmmV4PoolConfig,
  RaydiumClmmPoolConfig,
  RaydiumCpSwapPoolConfig,
  RaydiumLaunchlabPoolConfig,
  SaberPoolConfig,
  SanctumInfinityPoolConfig,
  SanctumStakePoolConfig,
  SarosDlmmPoolConfig,
  SauceSvmClient,
  ScaleAmmPoolConfig,
  ScaleVmmPoolConfig,
  ScorchPoolConfig,
  SendExecuteResult,
  SignedExecuteTransaction,
  SolayerPoolConfig,
  SolfiV1PoolConfig,
  SolfiV2PoolConfig,
  SplTokenSwapForkPoolConfig,
  StabbleClmmPoolConfig,
  StabbleStableSwapPoolConfig,
  StabbleWeightedSwapPoolConfig,
  StagedBuffer,
  SvmVenueLadder,
  SwapUser,
  TesseraVPoolConfig,
  TrendsPoolConfig,
  VaultLiquidUnstakePoolConfig,
  VenueAccount,
  VenueSwap,
  VirtualsPoolConfig,
  VoltrPoolConfig,
  WoofiPoolConfig,
  XorcaPoolConfig,
} from '../../../src/svm/index.js';

/**
 * Referencing every type in one tuple position keeps this fixture from ever
 * being "simplified" into an unused-import cleanup — its only job is to give
 * the TypeScript compiler API something to type-check.
 */
export type _ConsumerUnionTypeCheck = [
  AccountBytesMap,
  AccountLoader,
  AccountResolution,
  AldrinPoolConfig,
  AlphaqPoolConfig,
  BatchAccountLoader,
  BonkswapForkPoolConfig,
  ByrealPoolConfig,
  CarrotPoolConfig,
  CremaPoolConfig,
  CropperPoolConfig,
  DefiTunaPoolConfig,
  DeriversePoolConfig,
  EnsuredLookupTable,
  FluxBeamPoolConfig,
  GammaPoolConfig,
  GavelPoolConfig,
  GoonfiV2PoolConfig,
  HeavenPoolConfig,
  HumidiFiPoolConfig,
  HyloPoolConfig,
  HyloStabilityPoolConfig,
  HyloStabilityPoolDirection,
  InvariantPoolConfig,
  JupiterLendEarnPoolConfig,
  LadderSwapTemplate,
  LoadedAccount,
  MSwapPoolConfig,
  ManifestPoolConfig,
  MercurialPoolConfig,
  MetaDaoFutarchySpotPoolConfig,
  MeteoraDammV1StablePoolConfig,
  MeteoraDammV2PoolConfig,
  MeteoraDbcPoolConfig,
  MeteoraDlmmPoolConfig,
  MoonitPoolConfig,
  ObricV2PoolConfig,
  OmnipairPoolConfig,
  OpenBookV2PoolConfig,
  OrcaLegacyPoolConfig,
  OrcaWhirlpoolPoolConfig,
  PancakeswapClmmPoolConfig,
  PerenaPoolConfig,
  PerenaStarPoolConfig,
  PerpsJlpPoolConfig,
  PhoenixPoolConfig,
  PoolConfig,
  PumpfunBondingCurvePoolConfig,
  PumpswapPoolConfig,
  QuantumPoolConfig,
  RaydiumAmmV4PoolConfig,
  RaydiumClmmPoolConfig,
  RaydiumCpSwapPoolConfig,
  RaydiumLaunchlabPoolConfig,
  SaberPoolConfig,
  SanctumInfinityPoolConfig,
  SanctumStakePoolConfig,
  SarosDlmmPoolConfig,
  SauceSvmClient,
  ScaleAmmPoolConfig,
  ScaleVmmPoolConfig,
  ScorchPoolConfig,
  SendExecuteResult,
  SignedExecuteTransaction,
  SolayerPoolConfig,
  SolfiV1PoolConfig,
  SolfiV2PoolConfig,
  SplTokenSwapForkPoolConfig,
  StabbleClmmPoolConfig,
  StabbleStableSwapPoolConfig,
  StabbleWeightedSwapPoolConfig,
  StagedBuffer,
  SvmVenueLadder,
  SwapUser,
  TesseraVPoolConfig,
  TrendsPoolConfig,
  VaultLiquidUnstakePoolConfig,
  VenueAccount,
  VenueSwap,
  VirtualsPoolConfig,
  VoltrPoolConfig,
  WoofiPoolConfig,
  XorcaPoolConfig,
];
