/**
 * Consumer-union barrel-surface check -- the omission-catching counterpart to
 * migrated-barrel-surface.test.ts (see that file's header for the full
 * distinction). That sibling test asserts the migration's OWN emitted name
 * list against itself -- it re-derives its 474 names by reading the very
 * `venues/index.ts` lines it is meant to guard, so a name the migration never
 * thought to export at all is invisible to it by construction. This is
 * exactly how `SvmHyloDriftError`'s earlier absence from the barrel survived
 * that test unnoticed.
 *
 * This test instead asserts against an INDEPENDENTLY-SOURCED list: every
 * symbol name the downstream `sauce-recipes` package actually consumes,
 * extracted mechanically from ITS source tree, not from anything in this
 * repo. A name omitted here fails in the SDK, at PR time -- not one repo
 * away, after a re-pin.
 *
 * DERIVATION. In the `sauce-recipes` repo, over `ecoswap/svm/**`,
 * `solswap/**`, and `test/svm/**`: take the union of every named import (a)
 * sourced directly from `'@eco-incorp/sauce-sdk/svm'` today (names already
 * satisfied by pre-existing venues, e.g. `raydium-clmm`, `orca-whirlpool`,
 * `woofi`, `quantum`, `deriverse`, `goonfi-v2` -- all merged to this SDK
 * before this migration and unaffected by it), UNION (b) every named import
 * sourced from one of the 44 LOCAL venue module files THIS migration deletes
 * (`ecoswap/svm/venues/<key>.ts` or `<key>/{index,ladder}.ts`, for each of
 * the 44 keys this PR adds under `sdk/src/svm/venues/`) -- because once the
 * sauce-recipes-side companion re-pin lands, every such import becomes a
 * barrel import instead, and (a) alone would miss every migrated name that
 * isn't imported from the barrel yet. Import sites INSIDE the 44
 * soon-to-be-deleted local files themselves are excluded as sources (they
 * won't exist to import anything once deleted); every other file in the
 * three dirs above -- including the per-venue unit-test files under
 * `test/svm/venues/*.test.ts`, which keep testing the same logic
 * post-migration -- is a real, surviving consumer.
 *
 * 429 names total: 346 VALUES (below) + 83 TYPES
 * (consumer-union-types.fixture.ts). 279 of the 346 values (and all but a
 * handful of the types) are NOT satisfiable by `origin/main` today -- they
 * name one of the 44 newly-migrated venues. Measured directly (two full
 * `pnpm build`s, one per commit, this exact list run against each built
 * `sdk/dist/svm/index.js`): 232 of the 346 values and 45 of the 83 types are
 * UNDEFINED / unresolvable against `origin/main`'s dist (277 total), and 0 of
 * either are unresolvable against this branch's dist (post `SvmHyloDriftError`
 * fix). That gap is the non-vacuity proof for this test: an omission here is
 * not a hypothetical, it is what the barrel looked like one commit ago.
 *
 * VALUES are probed as runtime values against the built module namespace --
 * the exact thing a real `import { X } from '@eco-incorp/sauce-sdk/svm'`
 * needs. TYPES have no runtime presence and this package's `jest.config.cjs`
 * runs ts-jest with `diagnostics: false`, so a bare `import type { Foo }`
 * that names a missing export is SILENTLY ERASED at transpile time and would
 * never fail a jest run by itself -- to make the type half load-bearing, the
 * third test below drives the TypeScript compiler API directly (in-process,
 * not a subprocess) against `consumer-union-types.fixture.ts`, a file whose
 * only job is to import every listed type and reference each in one tuple
 * position, and asserts zero diagnostics.
 */
import * as svm from '../../../src/svm/index.js';
import ts from 'typescript';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

const CONSUMER_UNION_VALUES: readonly string[] = [
  'ALPHAQ_PROGRAM_ID',
  'BIN_ARRAY_DISCRIMINATOR',
  'BYREAL_PROGRAM_ID',
  'CARROT_MAX_ASSETS',
  'CARROT_PROGRAM_ID',
  'CARROT_VAULT_ADDRESS',
  'CLMMPOOL_ACCOUNT_SIZE',
  'CLMMPOOL_DISCRIMINATOR',
  'CREMA_PROGRAM_ID',
  'CROPPER_PROGRAM_ID',
  'CRT_MINT',
  'DEFITUNA_PROGRAM_ID',
  'FLUXBEAM_POOL_SIZE',
  'FLUXBEAM_PROGRAM_ID',
  'FUSION_POOL_ACCOUNT_SIZE',
  'FUSION_POOL_DISCRIMINATOR',
  'GAVEL_POOL_DISCRIMINANT',
  'GAVEL_POOL_SIZE',
  'GAVEL_PROGRAM_ID',
  'HUMIDIFI_AMOUNT_XOR_MASK',
  'HUMIDIFI_POOL_REGISTRY',
  'HUMIDIFI_PROGRAM_ID',
  'HYLO_ACCOUNT',
  'HYLO_PROGRAM_ID',
  'HYLO_STABILITY_POOL_CONFIG',
  'HYLO_STABILITY_POOL_LP_TOKEN_MINT',
  'HYLO_STABILITY_POOL_PROGRAM_ID',
  'HYLO_STABILITY_POOL_STABLECOIN_MINT',
  'HYUSD_MINT',
  'INSTRUCTIONS_SYSVAR',
  'INVARIANT_MAX_BOUNDARIES',
  'INVARIANT_PROGRAM_ID',
  'LB_PAIR_DISCRIMINATOR',
  'MANIFEST_MAX_ORDERS',
  'MANIFEST_PROGRAM_ID',
  'MARKET_DISCRIMINANT',
  'MARKET_FIXED_SIZE',
  'MAX_SQRT_PRICE_X64',
  'MERCURIAL_PROGRAM_ID',
  'METADAO_FUTARCHY_PROGRAM_ID',
  'METEORA_DLMM_MAX_BINS',
  'MINT_SUPPLY_OFFSET',
  'MIN_SQRT_PRICE_X64',
  'MSWAP_PROGRAM_ID',
  'M_MINT',
  'M_TOKEN_PROGRAM',
  'NIL',
  'OMNIPAIR_PROGRAM_ID',
  'OPENBOOK_V2_MAX_ORDERS',
  'OPENBOOK_V2_PROGRAM_ID',
  'ORCA_MINT_ID',
  'ORCA_WHIRLPOOL_PROGRAM_ID',
  'PAIR_ACCOUNT_SIZE',
  'PAIR_DISCRIMINATOR',
  'POOL_ACCOUNT_SIZE',
  'POOL_DISCRIMINATOR',
  'PUMPFUN_BONDING_CURVE_PROGRAM_ID',
  'RAYDIUM_CLMM_AMM_CONFIG_DISCRIMINATOR',
  'RAYDIUM_CLMM_MAX_BOUNDARIES',
  'RAYDIUM_CLMM_POOL_DISCRIMINATOR',
  'RAYDIUM_CLMM_TICK_ARRAY_DISCRIMINATOR',
  'RAYDIUM_LAUNCHLAB_PROGRAM_ID',
  'RAYDIUM_MAX_TICK',
  'RAYDIUM_MIN_TICK',
  'SAROS_DLMM_MAX_BINS',
  'SCORCH_CORE_PROGRAM_ID',
  'SCORCH_HAIRCUT_PPM',
  'SCORCH_ROUTER_PROGRAM_ID',
  'SOLAYER_PROGRAM_ID',
  'SOLAYER_SSOL_MINT',
  'SOLFI_V1_PROGRAM_ID',
  'SPL_TOKEN_PROGRAM_ID',
  'STATE_ESCROWED_OFFSET',
  'SWAP_GLOBAL_ID',
  'SWAP_M_ACCOUNT',
  'SvmHyloDriftError',
  'TICK_ACCOUNT_SIZE',
  'TICK_ARRAY_ACCOUNT_SIZE',
  'TICK_ARRAY_DISCRIMINATOR',
  'TICK_ARRAY_MAP_DISCRIMINATOR',
  'TICK_DISCRIMINATOR',
  'TRENDS_CONFIG_PDA',
  'TRENDS_EVENT_AUTHORITY',
  'TRENDS_POOL_AUTHORITY',
  'TRENDS_PROGRAM_ID',
  'USDC_COLLATERAL_VAULT',
  'USDC_MINT',
  'USDC_PAIR_ACCOUNT',
  'USDC_USD_PYTH_FEED',
  'USER_VOLUME_ACCUMULATOR_REF',
  'VAULT_AMOUNT_OFFSET',
  'VIRTUALS_MINT',
  'VOLTR_PROGRAM_ID',
  'WHIRLPOOL_ACCOUNT_SIZE',
  'WHIRLPOOL_DISCRIMINATOR',
  'WHIRLPOOL_MAX_BOUNDARIES',
  'WSOL_MINT',
  'XORCA_MINT_ID',
  'XORCA_PROGRAM_ID',
  'XORCA_STATE_PDA',
  'XORCA_VAULT_ATA',
  '_bakeCoefficientsForTest',
  '_isqrtForTest',
  '_referenceBuyForTest',
  '_referenceSellForTest',
  'aldrin',
  'aldrinLadder',
  'aldrinV2',
  'aldrinV2Ladder',
  'alphaqLadder',
  'bonkswap',
  'bonkswapLadder',
  'buildAtaPrepend',
  'buildCloseBufferInstruction',
  'buildComputeBudgetPrepend',
  'buildExecuteFromAccountInstruction',
  'buildExecuteInstruction',
  'buildExecuteTransaction',
  'buildFinalizeBufferInstruction',
  'buildHeapFramePrepend',
  'buildInitBufferInstructions',
  'buildStagingPlan',
  'buildWriteBufferInstruction',
  'byreal',
  'byrealLadder',
  'byrealWindowFor',
  'carrot',
  'carrotAllDirections',
  'carrotApplyDirection',
  'carrotGate',
  'carrotLadder',
  'carrotMints',
  'classifyVenue',
  'coalescingAccountLoader',
  'crema',
  'cremaLadder',
  'cremaWindowFor',
  'cropper',
  'cropperLadder',
  'defituna',
  'defitunaLadder',
  'defitunaWindowFor',
  'deriveBufferPda',
  'deriverse',
  'deriverseLadder',
  'dexlab',
  'dexlabLadder',
  'dlmmBinArrayIndex',
  'dlmmPriceFromId',
  'encodePayloadArgs',
  'fetchAlphaqPoolConfig',
  'fetchByrealPoolConfig',
  'fetchCremaPoolConfig',
  'fetchDefiTunaPoolConfig',
  'fetchFluxBeamPoolConfig',
  'fetchGavelConfig',
  'fetchHumidifiConfig',
  'fetchInvariantPoolConfig',
  'fetchMSwapPoolConfig',
  'fetchManifestConfig',
  'fetchMercurialPoolConfig',
  'fetchMetaDaoFutarchySpotConfig',
  'fetchMeteoraDlmmConfig',
  'fetchOmnipairPoolConfig',
  'fetchOpenBookV2Config',
  'fetchOrcaWhirlpoolConfig',
  'fetchPancakeswapClmmConfig',
  'fetchQuantumConfig',
  'fetchRaydiumClmmConfig',
  'fetchSarosDlmmConfig',
  'fetchSolfiV1Config',
  'fetchTrendsPoolConfig',
  'fetchVoltrConfig',
  'fetchXorcaConfig',
  'fluxbeam',
  'fluxbeamLadder',
  'gamma',
  'gammaLadder',
  'gavel',
  'gavelLadder',
  'getTransactionSize',
  'goonfiV2',
  'goonfiV2Ladder',
  'guacswap',
  'guacswapLadder',
  'heaven',
  'heavenApplyDirection',
  'heavenLadder',
  'heavenMints',
  'humidifiLadder',
  'hylo',
  'hyloGate',
  'hyloLadder',
  'hyloMintOut',
  'hyloRedeemCapacity',
  'hyloRedeemOut',
  'hyloStabilityPool',
  'hyloStabilityPoolLadder',
  'invariant',
  'invariantComputeSwapStepIn',
  'invariantDeltaX',
  'invariantDeltaY',
  'invariantLadder',
  'invariantNextSqrtXUp',
  'invariantNextSqrtYDown',
  'invariantSqrtPriceAtTick',
  'invariantWindowFor',
  'isqrt',
  'jupiterLendEarn',
  'jupiterLendEarnLadder',
  'manifest',
  'manifestBaseForQuote',
  'manifestLadder',
  'manifestQuoteForBase',
  'manifestWindowFor',
  'mercurial',
  'mercurialLadder',
  'metadaoFutarchySpotLadder',
  'meteoraDammV1Stable',
  'meteoraDammV1StableLadder',
  'meteoraDammV2',
  'meteoraDammV2Ladder',
  'meteoraDbc',
  'meteoraDbcLadder',
  'meteoraDlmm',
  'meteoraDlmmLadder',
  'meteoraDlmmWindowArrayIndexes',
  'meteoraDlmmWindowFor',
  'moonit',
  'moonitLadder',
  'mswap',
  'mswapLadder',
  'mswapPoolKey',
  'obricV2',
  'obricV2Ladder',
  'omnipair',
  'omnipairCapacity',
  'omnipairLadder',
  'omnipairQuote',
  'openbookV2Ladder',
  'openbookV2WindowFor',
  'orcaLegacyTokenSwap',
  'orcaLegacyTokenSwapLadder',
  'orcaV1',
  'orcaV1Ladder',
  'orcaWhirlpool',
  'orcaWhirlpoolLadder',
  'pairArrayIndexes',
  'pancakeswapClmm',
  'pancakeswapClmmLadder',
  'parseCarrotDirection',
  'penguin',
  'penguinLadder',
  'perena',
  'perenaLadder',
  'perenaStar',
  'perenaStarLadder',
  'perpsJlp',
  'perpsJlpLadder',
  'phoenix',
  'phoenixLadder',
  'phoenixPatchDivisor',
  'phoenixWindowFor',
  'priceFromId',
  'pumpfunBondingCurve',
  'pumpfunBondingCurveAssociatedUserVolumeAccumulator',
  'pumpfunBondingCurveLadder',
  'pumpfunBondingCurveUserVolumeAccumulatorPda',
  'pumpswapAdapter',
  'pumpswapLadder',
  'quantum',
  'quantumLadder',
  'quantumWindowFor',
  'raydiumAmmV4',
  'raydiumAmmV4Ladder',
  'raydiumClmm',
  'raydiumClmmArrayStartIndex',
  'raydiumClmmLadder',
  'raydiumClmmWindowFor',
  'raydiumClmmWindowStartTicks',
  'raydiumCpSwap',
  'raydiumCpSwapLadder',
  'raydiumDelta0',
  'raydiumDelta1',
  'raydiumLaunchlab',
  'raydiumLaunchlabLadder',
  'raydiumSqrtPriceAtTick',
  'readUintLE',
  'resolveAccounts',
  'saberStableswap',
  'saberStableswapLadder',
  'sanctumInfinity',
  'sanctumInfinityLadder',
  'sanctumInfinityPoolKey',
  'sanctumStakePool',
  'sanctumStakePool2',
  'sanctumStakePool2Ladder',
  'sanctumStakePool3',
  'sanctumStakePool3Ladder',
  'sanctumStakePool4',
  'sanctumStakePool4Ladder',
  'sanctumStakePoolLadder',
  'saros',
  'sarosDlmm',
  'sarosLadder',
  'scaleAmm',
  'scaleAmmLadder',
  'scaleVmm',
  'scaleVmmLadder',
  'scorch',
  'scorchLadder',
  'selectAltAddresses',
  'solayer',
  'solayerLadder',
  'solfiV1Ladder',
  'solfiV2',
  'solfiV2Ladder',
  'stabbleClmm',
  'stabbleClmmLadder',
  'stabbleStableSwap',
  'stabbleStableSwapLadder',
  'stabbleWeightedSwap',
  'stabbleWeightedSwapLadder',
  'staticCpiScreen',
  'stepn',
  'stepnLadder',
  'tesserav',
  'tesseravLadder',
  'tokenSwapV1',
  'tokenSwapV1Ladder',
  'trends',
  'trendsLadder',
  'vaultLiquidUnstake',
  'vaultLiquidUnstakeLadder',
  'venueAdapter',
  'virtuals',
  'virtualsLadder',
  'voltrLadder',
  'whirlpoolDeltaA',
  'whirlpoolDeltaB',
  'whirlpoolSqrtPriceAtTick',
  'windowFor',
  'windowStartTicks',
  'woofi',
  'woofiLadder',
  'xorcaLadder',
];

const CONSUMER_UNION_TYPES: readonly string[] = [
  'AccountBytesMap',
  'AccountLoader',
  'AccountResolution',
  'AldrinPoolConfig',
  'AlphaqPoolConfig',
  'BatchAccountLoader',
  'BonkswapForkPoolConfig',
  'ByrealPoolConfig',
  'CarrotPoolConfig',
  'CremaPoolConfig',
  'CropperPoolConfig',
  'DefiTunaPoolConfig',
  'DeriversePoolConfig',
  'EnsuredLookupTable',
  'FluxBeamPoolConfig',
  'GammaPoolConfig',
  'GavelPoolConfig',
  'GoonfiV2PoolConfig',
  'HeavenPoolConfig',
  'HumidiFiPoolConfig',
  'HyloPoolConfig',
  'HyloStabilityPoolConfig',
  'HyloStabilityPoolDirection',
  'InvariantPoolConfig',
  'JupiterLendEarnPoolConfig',
  'LadderSwapTemplate',
  'LoadedAccount',
  'MSwapPoolConfig',
  'ManifestPoolConfig',
  'MercurialPoolConfig',
  'MetaDaoFutarchySpotPoolConfig',
  'MeteoraDammV1StablePoolConfig',
  'MeteoraDammV2PoolConfig',
  'MeteoraDbcPoolConfig',
  'MeteoraDlmmPoolConfig',
  'MoonitPoolConfig',
  'ObricV2PoolConfig',
  'OmnipairPoolConfig',
  'OpenBookV2PoolConfig',
  'OrcaLegacyPoolConfig',
  'OrcaWhirlpoolPoolConfig',
  'PancakeswapClmmPoolConfig',
  'PerenaPoolConfig',
  'PerenaStarPoolConfig',
  'PerpsJlpPoolConfig',
  'PhoenixPoolConfig',
  'PoolConfig',
  'PumpfunBondingCurvePoolConfig',
  'PumpswapPoolConfig',
  'QuantumPoolConfig',
  'RaydiumAmmV4PoolConfig',
  'RaydiumClmmPoolConfig',
  'RaydiumCpSwapPoolConfig',
  'RaydiumLaunchlabPoolConfig',
  'SaberPoolConfig',
  'SanctumInfinityPoolConfig',
  'SanctumStakePoolConfig',
  'SarosDlmmPoolConfig',
  'SauceSvmClient',
  'ScaleAmmPoolConfig',
  'ScaleVmmPoolConfig',
  'ScorchPoolConfig',
  'SendExecuteResult',
  'SignedExecuteTransaction',
  'SolayerPoolConfig',
  'SolfiV1PoolConfig',
  'SolfiV2PoolConfig',
  'SplTokenSwapForkPoolConfig',
  'StabbleClmmPoolConfig',
  'StabbleStableSwapPoolConfig',
  'StabbleWeightedSwapPoolConfig',
  'StagedBuffer',
  'SvmVenueLadderV2',
  'SwapUser',
  'TesseraVPoolConfig',
  'TrendsPoolConfig',
  'VaultLiquidUnstakePoolConfig',
  'VenueAccount',
  'VenueSwap',
  'VirtualsPoolConfig',
  'VoltrPoolConfig',
  'WoofiPoolConfig',
  'XorcaPoolConfig',
];

describe('consumer-union barrel surface (sauce-recipes)', () => {
  it('pins the expected counts (346 values, 83 types) so a future edit is deliberate', () => {
    expect(CONSUMER_UNION_VALUES.length).toBe(346);
    expect(CONSUMER_UNION_TYPES.length).toBe(83);
  });

  it('every consumer-union VALUE resolves through the built @eco-incorp/sauce-sdk/svm barrel', () => {
    const missing = CONSUMER_UNION_VALUES.filter((name) => (svm as Record<string, unknown>)[name] === undefined);
    expect(missing).toEqual([]);
  });

  it('every consumer-union TYPE resolves -- checked via the TypeScript compiler API against the fixture', () => {
    const fixturePath = join(HERE, 'consumer-union-types.fixture.ts');
    const program = ts.createProgram([fixturePath], {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.ESNext,
      moduleResolution: ts.ModuleResolutionKind.Bundler,
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      noEmit: true,
    });
    const diagnostics = ts
      .getPreEmitDiagnostics(program)
      .filter((d) => d.file?.fileName === fixturePath)
      .map((d) => ts.flattenDiagnosticMessageText(d.messageText, '\n'));
    expect(diagnostics).toEqual([]);
  });

  it('sanity: every CONSUMER_UNION_TYPES name is absent from CONSUMER_UNION_VALUES (no double-classification)', () => {
    const valueSet = new Set(CONSUMER_UNION_VALUES);
    const overlap = CONSUMER_UNION_TYPES.filter((name) => valueSet.has(name));
    expect(overlap).toEqual([]);
  });
});
