/**
 * Venue-adapter framework for the multi-venue solswap recipe: one adapter per
 * on-chain venue (raydium, pumpswap, orca, saber, meteora, ...) that decodes
 * pool state off-chain, emits the in-VM SauceScript quote fragment, builds the
 * venue's swap CPI, and mirrors the quote math in TS for tests.
 */
import type { Address } from '@solana/kit';

/**
 * RPC-or-fixture account source: address in, raw account data out (null when
 * the account does not exist). fetchPoolConfig takes one of these so LiteSVM
 * fixture tests run without any RPC.
 */
export type AccountLoader = (address: Address) => Promise<Uint8Array | null>;

/**
 * Point-in-time account state keyed by base58 address — what referenceQuote
 * reads instead of the chain.
 */
export type AccountBytesMap = Record<string, Uint8Array>;

/**
 * Base shape of a decoded pool configuration. Each adapter extends it with
 * the venue-specific fields its quote emitter and swap builder need (vault
 * addresses, fee parameters, curve constants, ...) — everything is resolved
 * once, off-chain, by fetchPoolConfig.
 */
export interface PoolConfig {
  /** Slug of the adapter that produced this config. */
  venue: string;
  /** Pool state account address. */
  pool: Address;
}

/**
 * One account attached to the generated program. `ref` is the symbolic
 * account-plan ref used in generated SauceScript; `address` is present when
 * the adapter resolved it from PoolConfig and absent for caller-resolved refs
 * (the user's token accounts / owner from SwapUser).
 */
export interface VenueAccount {
  ref: string;
  address?: Address;
  writable?: boolean;
  signer?: boolean;
}

/**
 * User-side refs for buildSwap. Refs, not addresses: the caller resolves them
 * (resolveAccounts) when sending.
 */
export interface SwapUser {
  /** Ref of the user's output-token account. */
  outAta: string;
  /** Ref of the user's input-token account. */
  inAta: string;
  /** Ref of the user's wallet — token authority, attached as signer. */
  owner: string;
}

/**
 * A ready-to-CPI venue swap: raw instruction data plus its ordered accounts.
 * Venue-level min_out is always 1 — the recipe's post-swap outAta delta check
 * enforces the real bound.
 */
export interface VenueSwap {
  /** CALL target program id, baked into the bytecode. */
  programId: Address;
  /** Raw instruction data, discriminator included. */
  data: Uint8Array;
  /** Ordered exactly as the venue instruction expects. */
  accounts: VenueAccount[];
}

/**
 * A ladder swap CPI template (adapter contract v2, the EcoSwapSVM recipe):
 * the instruction data is `prefix ++ patched u64 LE ++ suffix`, with the u64
 * written at RUNTIME by the generated bytecode from the merge result — the
 * slot's input slice ('in', every real venue) or its predicted output ('out',
 * used by transfer stand-ins in engine tests). Venue-level min_out rides the
 * suffix as 1 — the recipe's single terminal outAta delta check enforces the
 * real bound across all slots at once.
 */
export interface LadderSwapTemplate {
  /** CALL target program id, baked into the bytecode (must be attached). */
  programId: Address;
  /** Instruction data before the patched u64 LE amount (discriminator/tag). */
  prefix: Uint8Array;
  /** Instruction data after the patched amount (min_out etc.; may be empty). */
  suffix: Uint8Array;
  /** Which runtime value lands in the patch slot. */
  patch: 'in' | 'out';
  /** Ordered exactly as the venue instruction expects (slot-role or user refs). */
  accounts: VenueAccount[];
}

/**
 * Adapter contract v2 — amount-PARAMETRIC fragments for the EcoSwapSVM
 * ladder solver. Unlike SvmVenueAdapter.emitQuote (which folds the trade
 * amount into compile-time constants), a v2 fragment reads the trade amount
 * and the live reserves at RUNTIME: reserves via accountUint over slot-role
 * refs (`s<i>:*`), the amount and per-slot params via the staged payload-args
 * cfg. One compiled blob per SHAPE (ordered family slots, see shapeKey)
 * serves any matching pool set — pool accounts rebind per trade through the
 * resolution map, per-trade values ride the payload args.
 */
export interface SvmVenueLadderV2 {
  slug: string;
  /**
   * Shape discriminant: pools sharing a shapeKey compile to byte-identical
   * slot fragments (direction and optional-account layout are part of it).
   */
  shapeKey(cfg: PoolConfig): string;
  /** Quote-helper function name (helpers are deduped by name across slots). */
  helperName(cfg: PoolConfig): string;
  /**
   * The family quote helper `function <name>(x, ...) { ... }`: a pure scalar
   * function of the gross input x and passed-in live state/params (helpers
   * cannot call helpers or read accounts/args themselves). Returns 0 for
   * x == 0 and for inputs the venue would reject (dust).
   */
  helperSource(cfg: PoolConfig): string;
  /** Per-slot scalar params the fragment consumes (beyond the shared enable flag). */
  paramCount: number;
  /** Per-trade values for those params, in emitSetup order. */
  paramsFor(cfg: PoolConfig): bigint[];
  /** Accounts the setup fragment reads (attached READ-ONLY; slot-role refs with resolved addresses). */
  quoteRefs(cfg: PoolConfig, slot: number): VenueAccount[];
  /**
   * Main-body lines binding the slot locals (`s<i>rin` etc.) from LIVE
   * accountUint reads plus the param locals (`params[k]` is the SauceScript
   * expression of per-slot param k).
   */
  emitSetup(cfg: PoolConfig, slot: number, params: readonly string[]): string;
  /** Quote-call expression for the gross-input expression `x` over the slot locals. */
  emitQuoteCall(cfg: PoolConfig, slot: number, x: string): string;
  /** The venue swap CPI as a runtime-patchable template (patch: 'in'). */
  buildSwapV2(cfg: PoolConfig, slot: number, user: SwapUser): LadderSwapTemplate;
  /**
   * TS mirror of the emitted quote: an exact integer closure over the SAME
   * live account bytes and params the fragment reads — the solver-reference
   * (and quoteEcoSwapSvm) evaluates it lamport-identically to the engine.
   */
  referenceQuote(cfg: PoolConfig, state: AccountBytesMap, params: readonly bigint[]): (x: bigint) => bigint;
  /** Effective (reserveIn, reserveOut) from state — relative-depth filter + continuous-oracle input. */
  depthReserves(cfg: PoolConfig, state: AccountBytesMap): { reserveIn: bigint; reserveOut: bigint };
  /**
   * Continuous-oracle fee model (ppm-scaled): out(x) ~= mu * (gamma*x*rOut) /
   * (rIn + gamma*x) with gamma = gammaPpm/1e6, mu = muPpm/1e6. Measurement
   * only (the optimal.ts efficiency oracle) — never a gate.
   */
  continuousFees(cfg: PoolConfig, state: AccountBytesMap, params: readonly bigint[]): { gammaPpm: bigint; muPpm: bigint };
}

export interface SvmVenueAdapter {
  slug: string;
  kind: 'constant-product' | 'stable' | 'sqrt-price';
  /** Mainnet program id. */
  programId: Address;
  /**
   * Off-chain, once per pool: fetch + decode the pool account (and its
   * config/vault deps), returning everything the emitter and swap builder
   * need. Accepts raw account data via the AccountLoader so LiteSVM fixtures
   * work without RPC. Throws a clear error naming the gate when the pool is
   * out of scope (status bits, curve_type, depeg, transfer-fee extensions).
   */
  fetchPoolConfig(load: AccountLoader, pool: Address): Promise<PoolConfig>;
  /** Accounts to attach READ-ONLY for quoting (refs + resolved addresses from PoolConfig). */
  quoteAccounts(cfg: PoolConfig): VenueAccount[];
  /**
   * SauceScript fragment computing `const q<i> = <amountOut>` for exactIn
   * amountIn (bigint literal baked). May call shared helper functions
   * (declared once by the generator).
   */
  emitQuote(cfg: PoolConfig, i: number, amountIn: bigint): string;
  /**
   * Swap CPI: raw instruction data + ordered account entries; venue-level
   * min_out set to 1 (the post-swap delta check enforces the real bound).
   */
  buildSwap(cfg: PoolConfig, user: SwapUser, amountIn: bigint): VenueSwap;
  /**
   * TS mirror of emitQuote for tests — MUST be independently derived from the
   * venue's quote formula in docs/svm-venues.md, not from reading the emitted
   * SauceScript. `state`
   * carries the accounts emitQuote reads; `now` is the unix timestamp for
   * time-dependent venues (amp ramps, locked-profit decay).
   */
  referenceQuote(cfg: PoolConfig, state: AccountBytesMap, amountIn: bigint, now: bigint): bigint;
}
