/**
 * Venue-adapter framework for the multi-venue solswap recipe: one adapter per
 * on-chain venue (raydium, pumpswap, orca, saber, meteora, ...) that decodes
 * pool state off-chain, emits the in-VM SauceScript quote fragment, builds the
 * venue's swap CPI, and mirrors the quote math in TS for tests.
 */
import type { Address } from '@solana/kit';

/**
 * RPC-or-fixture account source: address in, raw account data out (null when
 * the account does not exist). fetchPoolConfig takes one of these so LiteSVM
 * fixture tests run without any RPC.
 */
export type AccountLoader = (address: Address) => Promise<Uint8Array | null>;

/**
 * Point-in-time account state keyed by base58 address — what referenceQuote
 * reads instead of the chain.
 */
export type AccountBytesMap = Record<string, Uint8Array>;

/**
 * Base shape of a decoded pool configuration. Each adapter extends it with
 * the venue-specific fields its quote emitter and swap builder need (vault
 * addresses, fee parameters, curve constants, ...) — everything is resolved
 * once, off-chain, by fetchPoolConfig.
 */
export interface PoolConfig {
  /** Slug of the adapter that produced this config. */
  venue: string;
  /** Pool state account address. */
  pool: Address;
}

/**
 * One account attached to the generated program. `ref` is the symbolic
 * account-plan ref used in generated SauceScript; `address` is present when
 * the adapter resolved it from PoolConfig and absent for caller-resolved refs
 * (the user's token accounts / owner from SwapUser).
 */
export interface VenueAccount {
  ref: string;
  address?: Address;
  writable?: boolean;
  signer?: boolean;
  /**
   * quoteRefs only: the account may legitimately NOT EXIST on-chain (e.g. an
   * uninitialized whirlpool TickArray PDA beyond the readable window). The
   * orchestrator's state fetch skips it when missing instead of throwing;
   * the fragment must never read it (a param/live gate decides), though it
   * still rides the transaction account list for the venue CPI.
   */
  optional?: boolean;
}

/**
 * User-side refs for buildSwap. Refs, not addresses: the caller resolves them
 * (resolveAccounts) when sending.
 */
export interface SwapUser {
  /** Ref of the user's output-token account. */
  outAta: string;
  /** Ref of the user's input-token account. */
  inAta: string;
  /** Ref of the user's wallet — token authority, attached as signer. */
  owner: string;
}

/**
 * A ready-to-CPI venue swap: raw instruction data plus its ordered accounts.
 * Venue-level min_out is always 1 — the recipe's post-swap outAta delta check
 * enforces the real bound.
 */
export interface VenueSwap {
  /** CALL target program id, baked into the bytecode. */
  programId: Address;
  /** Raw instruction data, discriminator included. */
  data: Uint8Array;
  /** Ordered exactly as the venue instruction expects. */
  accounts: VenueAccount[];
}

/**
 * A ladder swap CPI template (adapter contract v2, the EcoSwapSVM recipe):
 * the instruction data is `prefix ++ patched u64 LE ++ suffix`, with the u64
 * written at RUNTIME by the generated bytecode from the merge result — the
 * slot's input slice ('in', every real venue) or its predicted output ('out',
 * used by transfer stand-ins in engine tests). Venue-level min_out rides the
 * suffix as 1 — the recipe's single terminal outAta delta check enforces the
 * real bound across all slots at once.
 */
export interface LadderSwapTemplate {
  /** CALL target program id, baked into the bytecode (must be attached). */
  programId: Address;
  /** Instruction data before the patched u64 LE amount (discriminator/tag). */
  prefix: Uint8Array;
  /** Instruction data after the patched amount (min_out etc.; may be empty). */
  suffix: Uint8Array;
  /** Which runtime value lands in the patch slot. */
  patch: 'in' | 'out';
  /** Ordered exactly as the venue instruction expects (slot-role or user refs). */
  accounts: VenueAccount[];
}

/**
 * Adapter contract v2 — amount-PARAMETRIC fragments for the EcoSwapSVM
 * ladder solver. Unlike SvmVenueAdapter.emitQuote (which folds the trade
 * amount into compile-time constants), a v2 fragment reads the trade amount
 * and the live reserves at RUNTIME: reserves via accountUint over slot-role
 * refs (`s<i>:*`), the amount and per-slot params via the staged payload-args
 * cfg. One compiled blob per SHAPE (ordered family slots, see shapeKey)
 * serves any matching pool set — pool accounts rebind per trade through the
 * resolution map, per-trade values ride the payload args.
 *
 * STABLE-STYLE families (Newton-iteration quotes) additionally implement the
 * statement-emitting ladder surface: `emitLadderQuote` threads warm-start
 * state between rungs (the invariant D is computed ONCE per trade in
 * emitSetup, each rung's Newton-y starts from the previous rung's y), and
 * `referenceLadderQuotes` mirrors that exact chain off-chain. The FINAL
 * per-slot quote (the predicted output the minOut check and the real-binary
 * quadrilateral see) always stays COLD — identical to the venue program's own
 * from-scratch iteration — via emitQuoteCall/referenceQuote.
 */
export interface SvmVenueLadderV2 {
  slug: string;
  /**
   * Default quote-ladder rungs for a slot of this family (the codegen input;
   * the CU budgeter may override per slot). Absent = 4 (the CP default);
   * stable families declare 2 — a Newton quote costs ~2 orders of magnitude
   * more CU than a CP quote, see recipes/ecoswap/svm/budget.ts.
   */
  defaultRungs?: number;
  /**
   * Shape discriminant: pools sharing a shapeKey compile to byte-identical
   * slot fragments (direction and optional-account layout are part of it).
   */
  shapeKey(cfg: PoolConfig): string;
  /**
   * Helper functions the family's fragments call — `function <name>(...) {}`
   * sources, pure scalar functions of their arguments (helpers cannot call
   * helpers or read accounts/args themselves). Deduped by NAME across slots
   * AND families (two families claiming one name must ship byte-identical
   * source — the codegen asserts it; that is how saber and meteora-damm-v1
   * share stableD/stableYW). A quote helper returns 0 for x == 0 and for
   * inputs the venue would reject (dust).
   */
  helpers(cfg: PoolConfig): { name: string; source: string }[];
  /** Per-slot scalar params the fragment consumes (beyond the shared enable flag). */
  paramCount: number;
  /** Per-trade values for those params, in emitSetup order. */
  paramsFor(cfg: PoolConfig): bigint[];
  /** Accounts the setup fragment reads (attached READ-ONLY; slot-role refs with resolved addresses). */
  quoteRefs(cfg: PoolConfig, slot: number): VenueAccount[];
  /**
   * Main-body lines binding the slot locals (`s<i>rin` etc.) from LIVE
   * accountUint reads plus the param locals (`params[k]` is the SauceScript
   * expression of per-slot param k). `enableVar` is the slot's enable-flag
   * local — adapters with EXPENSIVE setup (a stable slot's Newton D) gate
   * that work on it (`let` the local, assign inside `if (enableVar !== 0)`)
   * so a disabled slot costs only its unconditional account reads.
   */
  emitSetup(cfg: PoolConfig, slot: number, params: readonly string[], enableVar?: string): string;
  /**
   * Quote-call EXPRESSION for the gross-input expression `x` over the slot
   * locals — the CP form, used for ladder rungs and the final predicted
   * output alike. Absent for statement-form (stable) families, which provide
   * emitLadderQuote + emitFinalQuote instead.
   */
  emitQuoteCall?(cfg: PoolConfig, slot: number, x: string): string;
  /**
   * STABLE-STYLE ladders: statement lines that define `const <outVar>` = the
   * chain quote at cumulative grid point `x` for rung index `rung` (0-based),
   * threading warm-start locals between rungs by slot-scoped naming
   * (`s<slot>wy`). Rung 0 must seed the chain from the setup locals. Emitted
   * INSIDE the slot's enable-gated ladder block. When absent the codegen uses
   * `emitQuoteCall` per rung (CP families — pointwise == chain).
   */
  emitLadderQuote?(cfg: PoolConfig, slot: number, rung: number, x: string, outVar: string): string;
  /**
   * Statement lines that define `let <outVar>` = the COLD (venue-exact,
   * from-scratch) quote at expression `x` — the final predicted output.
   * Required alongside emitLadderQuote; must guard x == 0 (and disabled-slot
   * zeroed setup locals) to 0 without running the expensive path.
   */
  emitFinalQuote?(cfg: PoolConfig, slot: number, x: string, outVar: string): string;
  /** The venue swap CPI as a runtime-patchable template (patch: 'in'). */
  buildSwapV2(cfg: PoolConfig, slot: number, user: SwapUser): LadderSwapTemplate;
  /**
   * TS mirror of the emitted quote: an exact integer closure over the SAME
   * live account bytes and params the fragment reads — the solver-reference
   * (and quoteEcoSwapSvm) evaluates it lamport-identically to the engine.
   * `now` (unix seconds) feeds time-dependent families (locked-profit decay,
   * amp ramps) — it must equal the cluster clock the fragment's
   * block.timestamp reads for the lamport-exact gate to hold.
   */
  referenceQuote(cfg: PoolConfig, state: AccountBytesMap, params: readonly bigint[], now?: bigint): (x: bigint) => bigint;
  /**
   * Mirror of emitLadderQuote's warm-start chain: quotes the ORDERED
   * cumulative grid points with the same state threading, same integer ops,
   * same iteration counts. Absent = pointwise referenceQuote (CP families).
   */
  referenceLadderQuotes?(
    cfg: PoolConfig,
    state: AccountBytesMap,
    params: readonly bigint[],
    now?: bigint,
  ): (grid: readonly bigint[]) => bigint[];
  /**
   * CAPACITY-AWARE (window-walking) families only — orca-whirlpool,
   * raydium-clmm, meteora-dlmm, manifest. Names the slot-local that, after
   * every emitLadderQuote call, holds the CUMULATIVE PRODUCTIVE gross input of
   * the most recent rung: the grid point itself while the walk stays inside
   * the shipped-window capacity, or the productive input consumed when the
   * walk exhausts at c < grid point (the window/book cap). The codegen books
   * each rung's dIn from the DELTA of this local instead of the raw geometric
   * grid span, so a rung that exceeds capacity contributes only its productive
   * input (not the full span with a dead dOut) — the venue self-caps at its
   * real depth instead of losing every merge election past capacity. Absent =
   * dIn is the raw grid span (CP/stable families, no capacity limit —
   * byte-identical to the pre-capacity codegen).
   */
  capacityInputVar?(slot: number): string;
  /**
   * Off-chain mirror of capacityInputVar: the cumulative productive gross
   * input per ORDERED grid point, computed over the SAME walk referenceQuote
   * runs. Must equal the on-chain `capacityInputVar` local after each rung
   * lamport-for-lamport (both derive from the same exhaustion point) — that is
   * what keeps the capacity-clamped split reproducible. Present iff
   * capacityInputVar is.
   */
  referenceCapacities?(
    cfg: PoolConfig,
    state: AccountBytesMap,
    params: readonly bigint[],
    now?: bigint,
  ): (grid: readonly bigint[]) => bigint[];
  /**
   * Effective (reserveIn, reserveOut) from state — relative-depth filter +
   * continuous-oracle input. `now` as in referenceQuote.
   */
  depthReserves(cfg: PoolConfig, state: AccountBytesMap, now?: bigint): { reserveIn: bigint; reserveOut: bigint };
  /**
   * Continuous-oracle fee model (ppm-scaled): out(x) ~= mu * (gamma*x*rOut) /
   * (rIn + gamma*x) with gamma = gammaPpm/1e6, mu = muPpm/1e6. Measurement
   * only (the optimal.ts efficiency oracle) — never a gate. For stable
   * curves the CP form badly understates depth; their values are honest fee
   * retentions but the oracle stays meaningful only for CP-class venues.
   */
  continuousFees(cfg: PoolConfig, state: AccountBytesMap, params: readonly bigint[]): { gammaPpm: bigint; muPpm: bigint };
}

export interface SvmVenueAdapter {
  slug: string;
  kind: 'constant-product' | 'stable' | 'sqrt-price';
  /** Mainnet program id. */
  programId: Address;
  /**
   * Off-chain, once per pool: fetch + decode the pool account (and its
   * config/vault deps), returning everything the emitter and swap builder
   * need. Accepts raw account data via the AccountLoader so LiteSVM fixtures
   * work without RPC. Throws a clear error naming the gate when the pool is
   * out of scope (status bits, curve_type, depeg, transfer-fee extensions).
   */
  fetchPoolConfig(load: AccountLoader, pool: Address): Promise<PoolConfig>;
  /** Accounts to attach READ-ONLY for quoting (refs + resolved addresses from PoolConfig). */
  quoteAccounts(cfg: PoolConfig): VenueAccount[];
  /**
   * SauceScript fragment computing `const q<i> = <amountOut>` for exactIn
   * amountIn (bigint literal baked). May call shared helper functions
   * (declared once by the generator).
   */
  emitQuote(cfg: PoolConfig, i: number, amountIn: bigint): string;
  /**
   * Swap CPI: raw instruction data + ordered account entries; venue-level
   * min_out set to 1 (the post-swap delta check enforces the real bound).
   */
  buildSwap(cfg: PoolConfig, user: SwapUser, amountIn: bigint): VenueSwap;
  /**
   * TS mirror of emitQuote for tests — MUST be independently derived from the
   * venue's quote formula in docs/svm-venues.md, not from reading the emitted
   * SauceScript. `state`
   * carries the accounts emitQuote reads; `now` is the unix timestamp for
   * time-dependent venues (amp ramps, locked-profit decay).
   */
  referenceQuote(cfg: PoolConfig, state: AccountBytesMap, amountIn: bigint, now: bigint): bigint;
}
