/**
 * Solswap end-to-end on LiteSVM: the recipe's generated bytecode runs on the
 * real SVM engine, quoting 4 pool fixtures from account data, CPI-ing to the
 * single winning venue (a system-program transfer standing in for the venue
 * call) and returning bestOut. This is the Phase C dogfood: PDAs, account
 * resolution and the execute instruction all come from sdk/src/svm's pure
 * builders — the LiteSVM harness below only owns bank setup and signing.
 *
 * Requires the engine .so built by cargo build-sbf (SAUCE_ENGINE_SO or the
 * sauce checkout's svm/target/deploy/engine.so). The engine-bound suites skip
 * when it is absent (CI); the plan/budget suites always run.
 */
import { existsSync } from 'fs';
import { resolve } from 'path';
import {
  AccountRole,
  appendTransactionMessageInstructions,
  createTransactionMessage,
  generateKeyPairSigner,
  getAddressCodec,
  lamports,
  pipe,
  setTransactionMessageFeePayerSigner,
  signTransactionMessageWithSigners,
} from '@solana/kit';
import type { Address, KeyPairSigner } from '@solana/kit';
import { SYSTEM_PROGRAM_ADDRESS } from '@solana-program/system';
import { FailedTransactionMetadata, LiteSVM } from 'litesvm';
import { estimatePacket } from '@eco-incorp/sauce-compiler';
import {
  buildExecuteInstruction,
  deriveEnginePdas,
  PDA_FRAMES_BYTES,
  PDA_HEAP_BYTES,
  PDA_STACK_BYTES,
  resolveAccounts,
} from '../../src/svm/index.js';
import type { AccountResolution, EnginePda, EnginePdas } from '../../src/svm/index.js';
import { solswap, solswapQuote } from '../../src/recipes/solswap/index.js';
import type { SolswapConfig, SolswapOutput } from '../../src/recipes/solswap/index.js';

// sdk jest cwd is sdk/, so the default points at the sibling sauce checkout's
// engine build (same resolution rule as the compiler's LiteSVM harness).
const ENGINE_SO = process.env.SAUCE_ENGINE_SO ?? resolve(process.cwd(), '../../sauce/svm/target/deploy/engine.so');
const describeSvm = existsSync(ENGINE_SO) ? describe : describe.skip;

// ── fixtures ────────────────────────────────────────────────────────────────

const AMOUNT_IN = 1_000_000_000n;
const FUNDED = 1_000_000_000n;
/** 32 zero bytes — the system program id, the stand-in venue for the swap CPI. */
const SYSTEM_PROGRAM_ID_BYTES = new Uint8Array(32);

interface PoolFixture {
  reserveIn: bigint;
  reserveOut: bigint;
  feeBps: bigint;
  /** Reserve word offsets differ per pool to prove they are honored per pool. */
  inOffset: number;
  outOffset: number;
  /** Baked into the pool's stand-in swap calldata; distinct per pool. */
  transferLamports: bigint;
}

// Reserve magnitudes are deliberately small (~2^40): engine arithmetic WRAPS,
// so fixtures stay far below any intermediate that could overflow the quote
// math (see the recipe's documented < 2^128 assumption).
const SCENARIO_POOL2_BEST: PoolFixture[] = [
  { reserveIn: 1_000_000_000_000n, reserveOut: 1_000_000_000_000n, feeBps: 30n, inOffset: 8, outOffset: 40, transferLamports: 1_000_000n },
  { reserveIn: 1_000_000_000_000n, reserveOut: 1_100_000_000_000n, feeBps: 25n, inOffset: 0, outOffset: 32, transferLamports: 2_000_000n },
  { reserveIn: 2_000_000_000_000n, reserveOut: 1_900_000_000_000n, feeBps: 30n, inOffset: 16, outOffset: 64, transferLamports: 3_000_000n },
  { reserveIn: 1_000_000_000_000n, reserveOut: 1_050_000_000_000n, feeBps: 100n, inOffset: 4, outOffset: 36, transferLamports: 4_000_000n },
];

// Same pools with pool 4's reserves boosted so the LAST branch wins.
const SCENARIO_POOL4_BEST: PoolFixture[] = SCENARIO_POOL2_BEST.map((pool, i) =>
  i === 3 ? { ...pool, reserveOut: 1_500_000_000_000n } : pool,
);

// Pool 4's economics copied from pool 2 so indices 1 and 3 quote identically —
// the tie fixture for the strictly-greater winner scan (offsets stay pool 4's
// own, proving offsets are honored independently of the tied economics).
const SCENARIO_TIE: PoolFixture[] = SCENARIO_POOL2_BEST.map((pool, i) =>
  i === 3
    ? {
        ...pool,
        reserveIn: SCENARIO_POOL2_BEST[1].reserveIn,
        reserveOut: SCENARIO_POOL2_BEST[1].reserveOut,
        feeBps: SCENARIO_POOL2_BEST[1].feeBps,
      }
    : pool,
);

// Independently recomputed expectations, pinned as numeric literals and NOT
// derived from solswapQuote — a formula bug shared between the recipe's
// off-chain mirror and its generated bytecode cannot self-verify against
// these. Derivation (from scratch, per pool):
//   out = ⌊amountIn·(10000−feeBps)·reserveOut / (reserveIn·10000 + amountIn·(10000−feeBps))⌋
const POOL2_QUOTES = [996_006_981n, 1_096_156_583n, 946_678_080n, 1_038_471_912n];
const POOL2_BEST = { bestIndex: 1, bestOut: 1_096_156_583n };
const POOL4_BEST = { bestIndex: 3, bestOut: 1_483_531_304n };
/** What SCENARIO_TIE's pools 1 and 3 both quote. */
const TIE_QUOTE = 1_096_156_583n;

/** SystemInstruction::Transfer: u32 LE discriminant 2 + u64 LE lamports. */
const systemTransferData = (amount: bigint): Uint8Array => {
  const data = new Uint8Array(12);
  const view = new DataView(data.buffer);
  view.setUint32(0, 2, true);
  view.setBigUint64(4, amount, true);
  return data;
};

const buildConfig = (pools: PoolFixture[], minOut: bigint): SolswapConfig => ({
  amountIn: AMOUNT_IN,
  minOut,
  pools: pools.map((pool, i) => ({
    ref: `pool${i}`,
    reserveInOffset: pool.inOffset,
    reserveOutOffset: pool.outOffset,
    feeBps: pool.feeBps,
    swap: {
      programRef: 'venueProgram',
      programId: SYSTEM_PROGRAM_ID_BYTES,
      calldata: systemTransferData(pool.transferLamports),
      accounts: [
        { ref: 'payer', writable: true, signer: true },
        { ref: `recipient${i}`, writable: true },
      ],
    },
  })),
});

/**
 * Off-chain mirror of the generated winner scan (strictly-greater tracking).
 * Validated against the pinned POOL2_BEST/POOL4_BEST constants below — the
 * engine-bound assertions use the pins, never this mirror, as ground truth.
 */
const expectedBest = (pools: PoolFixture[]): { bestOut: bigint; bestIndex: number } => {
  let bestOut = solswapQuote(AMOUNT_IN, pools[0].feeBps, pools[0].reserveIn, pools[0].reserveOut);
  let bestIndex = 0;
  for (let i = 1; i < pools.length; i++) {
    const quote = solswapQuote(AMOUNT_IN, pools[i].feeBps, pools[i].reserveIn, pools[i].reserveOut);
    if (quote > bestOut) {
      bestOut = quote;
      bestIndex = i;
    }
  }
  return { bestOut, bestIndex };
};

const writeBe256 = (data: Uint8Array, offset: number, value: bigint): void => {
  for (let i = 31; i >= 0; i--) {
    data[offset + i] = Number(value & 0xffn);
    value >>= 8n;
  }
};

const poolData = (pool: PoolFixture): Uint8Array => {
  const data = new Uint8Array(Math.max(pool.inOffset, pool.outOffset) + 32);
  writeBe256(data, pool.inOffset, pool.reserveIn);
  writeBe256(data, pool.outOffset, pool.reserveOut);
  return data;
};

// ── local LiteSVM harness (bank setup + signing only; everything engine- and
// plan-shaped comes from sdk/src/svm) ───────────────────────────────────────

interface Harness {
  svm: LiteSVM;
  programId: Address;
  payer: KeyPairSigner;
  pdas: EnginePdas;
}

const randomAddress = (): Address => getAddressCodec().decode(crypto.getRandomValues(new Uint8Array(32)));

const startEngine = async (): Promise<Harness> => {
  const svm = new LiteSVM();
  const programId = (await generateKeyPairSigner()).address;
  svm.addProgramFromFile(programId, ENGINE_SO);

  const payer = await generateKeyPairSigner();
  svm.airdrop(payer.address, lamports(1_000_000_000_000n));

  // Fast-path PDA provisioning: full-size zeroed data with the canonical bump
  // at data[0] — what the on-chain init growth loop builds, minus the
  // transactions (the init path itself is covered by instructions.test.ts).
  const pdas = await deriveEnginePdas(programId);
  const specs: [EnginePda, number][] = [
    [pdas.stack, PDA_STACK_BYTES],
    [pdas.heap, PDA_HEAP_BYTES],
    [pdas.frames, PDA_FRAMES_BYTES],
  ];
  for (const [pda, size] of specs) {
    const data = new Uint8Array(size);
    data[0] = pda.bump;
    svm.setAccount({
      address: pda.address,
      data,
      executable: false,
      lamports: lamports(svm.minimumBalanceForRentExemption(BigInt(size))),
      programAddress: programId,
      space: BigInt(size),
    });
  }

  return { svm, programId, payer, pdas };
};

interface Scenario {
  harness: Harness;
  output: SolswapOutput;
  resolution: AccountResolution;
  recipients: Address[];
}

const setupScenario = async (pools: PoolFixture[], minOut: bigint): Promise<Scenario> => {
  const harness = await startEngine();
  const output = solswap(buildConfig(pools, minOut));
  const resolution: AccountResolution = {};
  const recipients: Address[] = [];

  pools.forEach((pool, i) => {
    const poolAddress = randomAddress();
    const data = poolData(pool);
    harness.svm.setAccount({
      address: poolAddress,
      data,
      executable: false,
      lamports: lamports(harness.svm.minimumBalanceForRentExemption(BigInt(data.length))),
      programAddress: SYSTEM_PROGRAM_ADDRESS,
      space: BigInt(data.length),
    });
    resolution[`pool${i}`] = poolAddress;

    // Transfer recipients must be pre-funded so the exact credited delta is
    // observable on top of a known balance.
    const recipient = randomAddress();
    harness.svm.setAccount({
      address: recipient,
      data: new Uint8Array(0),
      executable: false,
      lamports: lamports(FUNDED),
      programAddress: SYSTEM_PROGRAM_ADDRESS,
      space: 0n,
    });
    recipients.push(recipient);
    resolution[`recipient${i}`] = recipient;
  });

  // No 'venueProgram' entry on purpose: the plan meta carries the pubkey the
  // recipe baked from swap.programId, and resolveAccounts binds it from there.
  return { harness, output, resolution, recipients };
};

type RunResult =
  | { ok: true; returnData: Uint8Array; logs: string[] }
  | { ok: false; revertData: Uint8Array; err: string; logs: string[] };

const execute = async ({ harness, output, resolution }: Scenario): Promise<RunResult> => {
  const accounts = resolveAccounts(output.accountPlan, resolution, harness.payer.address);
  const instruction = buildExecuteInstruction({
    programId: harness.programId,
    pdas: harness.pdas,
    bytecode: output.bytecode,
    accounts,
  });

  // A fresh blockhash per send keeps signatures unique — LiteSVM's history
  // rejects a byte-identical resend.
  harness.svm.expireBlockhash();

  const message = pipe(
    createTransactionMessage({ version: 0 }),
    (m) => setTransactionMessageFeePayerSigner(harness.payer, m),
    (m) => appendTransactionMessageInstructions([instruction], m),
    (m) => harness.svm.setTransactionMessageLifetimeUsingLatestBlockhash(m),
  );
  const transaction = await signTransactionMessageWithSigners(message);
  const result = harness.svm.sendTransaction(transaction);

  if (result instanceof FailedTransactionMetadata) {
    return {
      ok: false,
      revertData: result.meta().returnData().data(),
      err: String(result.err()),
      logs: result.meta().logs(),
    };
  }

  return { ok: true, returnData: result.returnData().data(), logs: result.logs() };
};

const expectOk = (result: RunResult): { returnData: Uint8Array; logs: string[] } => {
  if (!result.ok) throw new Error(`expected success, got: ${result.err}\n${result.logs.join('\n')}`);
  return result;
};

const expectFail = (result: RunResult): { revertData: Uint8Array; err: string; logs: string[] } => {
  if (result.ok) throw new Error('expected the transaction to fail, but it succeeded');
  return result;
};

const toBigInt = (bytes: Uint8Array): bigint =>
  bytes.length === 0 ? 0n : BigInt('0x' + Buffer.from(bytes).toString('hex'));

// ── engine-bound scenarios ──────────────────────────────────────────────────

describeSvm('solswap e2e: quote 4 pools in-VM, CPI the winner', () => {
  it('pool 2 has the best rate: its recipient is credited exactly, bestOut returned', async () => {
    const { bestOut, bestIndex } = POOL2_BEST;

    const scenario = await setupScenario(SCENARIO_POOL2_BEST, 1n);
    const result = expectOk(await execute(scenario));

    expect(toBigInt(result.returnData)).toBe(bestOut);
    scenario.recipients.forEach((recipient, i) => {
      const expected = i === bestIndex ? FUNDED + SCENARIO_POOL2_BEST[i].transferLamports : FUNDED;
      expect(scenario.harness.svm.getBalance(recipient)).toBe(expected);
    });
  });

  it('reserves permuted so pool 4 wins: only its recipient is credited', async () => {
    const { bestOut, bestIndex } = POOL4_BEST;

    const scenario = await setupScenario(SCENARIO_POOL4_BEST, 1n);
    const result = expectOk(await execute(scenario));

    expect(toBigInt(result.returnData)).toBe(bestOut);
    scenario.recipients.forEach((recipient, i) => {
      const expected = i === bestIndex ? FUNDED + SCENARIO_POOL4_BEST[i].transferLamports : FUNDED;
      expect(scenario.harness.svm.getBalance(recipient)).toBe(expected);
    });
  });

  it('exact quote tie between pools 2 and 4: the first-listed pool wins', async () => {
    const scenario = await setupScenario(SCENARIO_TIE, 1n);
    const result = expectOk(await execute(scenario));

    // The scan is strictly-greater, so index 1 keeps the win over the
    // identically-quoting index 3 — pool order is the tie-break.
    expect(toBigInt(result.returnData)).toBe(TIE_QUOTE);
    scenario.recipients.forEach((recipient, i) => {
      const expected = i === 1 ? FUNDED + SCENARIO_TIE[1].transferLamports : FUNDED;
      expect(scenario.harness.svm.getBalance(recipient)).toBe(expected);
    });
  });

  it('minOut exactly equal to bestOut passes (inclusive bound), winner credited', async () => {
    const scenario = await setupScenario(SCENARIO_POOL2_BEST, POOL2_BEST.bestOut);
    const result = expectOk(await execute(scenario));

    expect(toBigInt(result.returnData)).toBe(POOL2_BEST.bestOut);
    expect(scenario.harness.svm.getBalance(scenario.recipients[POOL2_BEST.bestIndex])).toBe(
      FUNDED + SCENARIO_POOL2_BEST[POOL2_BEST.bestIndex].transferLamports,
    );
  });

  it('minOut above every quote: tx fails with the minOut payload, no transfers', async () => {
    const scenario = await setupScenario(SCENARIO_POOL2_BEST, POOL2_BEST.bestOut + 1n);
    const failure = expectFail(await execute(scenario));

    expect(Buffer.from(failure.revertData).toString('utf8')).toBe('minOut');
    for (const recipient of scenario.recipients) {
      expect(scenario.harness.svm.getBalance(recipient)).toBe(FUNDED);
    }
  });
});

// ── quote math pins (no engine required) ────────────────────────────────────

describe('solswap quote math against independently pinned values', () => {
  it('solswapQuote reproduces every pinned fixture quote', () => {
    SCENARIO_POOL2_BEST.forEach((pool, i) => {
      expect(solswapQuote(AMOUNT_IN, pool.feeBps, pool.reserveIn, pool.reserveOut)).toBe(POOL2_QUOTES[i]);
    });
  });

  it('the winner-scan mirror agrees with the pinned winners', () => {
    expect(expectedBest(SCENARIO_POOL2_BEST)).toEqual(POOL2_BEST);
    expect(expectedBest(SCENARIO_POOL4_BEST)).toEqual(POOL4_BEST);
    // The tie fixture really ties: pools 1 and 3 quote the same value, and the
    // strictly-greater mirror resolves it to the earlier index.
    expect(solswapQuote(AMOUNT_IN, SCENARIO_TIE[3].feeBps, SCENARIO_TIE[3].reserveIn, SCENARIO_TIE[3].reserveOut)).toBe(TIE_QUOTE);
    expect(expectedBest(SCENARIO_TIE)).toEqual({ bestIndex: 1, bestOut: TIE_QUOTE });
  });
});

// ── plan / budget sanity (no engine required) ───────────────────────────────

describe('solswap account plan and packet budget', () => {
  const output = solswap(buildConfig(SCENARIO_POOL2_BEST, 1n));

  it('interns every pool, the venue program, the payer and each swap account in first-use order', () => {
    expect(output.accountPlan.metas.map((meta) => meta.ref)).toEqual([
      'pool0',
      'pool1',
      'pool2',
      'pool3',
      'venueProgram',
      'payer',
      'recipient0',
      'recipient1',
      'recipient2',
      'recipient3',
    ]);

    for (const pool of output.accountPlan.metas.slice(0, 4)) {
      expect(pool.writable).toBe(false);
      expect(pool.signer).toBe(false);
    }

    const payer = output.accountPlan.metas[5];
    expect(payer.writable).toBe(true);
    expect(payer.signer).toBe(true);

    expect(output.accountPlan.metas[4].pubkey).toBe(SYSTEM_PROGRAM_ADDRESS);
  });

  it('resolveAccounts binds the payer as writable signer and the venue via the baked pubkey', () => {
    const codec = getAddressCodec();
    const addressFor = (seed: number): Address => codec.decode(new Uint8Array(32).fill(seed));
    const payer = addressFor(0xaa);
    const resolution: AccountResolution = {};
    for (let i = 0; i < 4; i++) {
      resolution[`pool${i}`] = addressFor(i + 1);
      resolution[`recipient${i}`] = addressFor(i + 11);
    }

    const metas = resolveAccounts(output.accountPlan, resolution, payer);

    expect(metas).toHaveLength(output.accountPlan.metas.length);
    expect(metas[4]).toEqual({ address: SYSTEM_PROGRAM_ADDRESS, role: AccountRole.READONLY });
    expect(metas[5]).toEqual({ address: payer, role: AccountRole.WRITABLE_SIGNER });
    expect(metas[6]).toEqual({ address: addressFor(11), role: AccountRole.WRITABLE });
  });

  it('fits the packet budget with no warnings at this size', () => {
    expect(output.warnings).toEqual([]);

    const budget = estimatePacket(output.accountPlan, output.bytecode.length);
    expect(budget.warnings).toEqual([]);
    expect(budget.messageBytes).toBeLessThanOrEqual(budget.limitBytes);
  });
});

describe('solswap config validation', () => {
  it('rejects fewer than 2 pools', () => {
    const config = buildConfig(SCENARIO_POOL2_BEST, 1n);
    expect(() => solswap({ ...config, pools: config.pools.slice(0, 1) })).toThrow(
      'solswap expects 2 to 8 pools, got 1',
    );
  });

  it('rejects more than 8 pools', () => {
    const config = buildConfig([...SCENARIO_POOL2_BEST, ...SCENARIO_POOL2_BEST, SCENARIO_POOL2_BEST[0]], 1n);
    expect(() => solswap(config)).toThrow('solswap expects 2 to 8 pools, got 9');
  });

  it('rejects a program ref bound to two different program ids', () => {
    const config = buildConfig(SCENARIO_POOL2_BEST, 1n);
    config.pools[1].swap.programId = new Uint8Array(32).fill(7);
    expect(() => solswap(config)).toThrow(
      "solswap program ref 'venueProgram' is bound to two different program ids",
    );
  });
});
