/**
 * solswapBest generator units (no engine, no RPC): source-shape assertions
 * over the generated SauceScript — shared stable Newton helpers declared
 * exactly once, external quotes baked as constants, the strictly-greater
 * scan / pre-CPI minOut / dispatch / post-swap delta-check ordering — plus
 * account-plan pubkey stamping, budget-warning surfacing, and config
 * validation. Live pools come from the venue adapters' mainnet fixtures;
 * engine execution of the generated bytecode lands in the e2e phase.
 */
import { resolve } from 'path';
import { address } from '@solana/kit';
import { estimatePacket } from '@eco-incorp/sauce-compiler';
import { solswapBest } from '../../src/recipes/solswap/index.js';
import type { SolswapBestConfig, SolswapBestPool } from '../../src/recipes/solswap/index.js';
import type { VenueSwap } from '../../src/svm/index.js';
import { fixtureLoader, loadFixtures } from './fixtures.js';
import type { AccountFixture } from './fixtures.js';

// Fixture pools (real mainnet dumps, same as the per-adapter suites).
const SABER_POOL = address('YAkoNb6HKmSxQN9L8hiBE5tPJRsniSSMzND1boHmZxe');
const METEORA_V1_POOL = address('32D4zRxNc1EssbJieVHfPhZM3rH6CzfUPrWUuWxD9prG');
const CP_POOL = address('7JuwJuNU88gurFnyWeiyGKbFmExMWcmRZntn9imEzdny');

const SABER_PROGRAM = 'SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ';
const EXTERNAL_PROGRAM = address('ComputeBudget111111111111111111111111111111');
const EXTERNAL_POOL_STATE = address('BPFLoaderUpgradeab1e11111111111111111111111');

const fixturesDir = (slug: string) => resolve(process.cwd(), `test/svm/fixtures/${slug}`);
const allFixtures: AccountFixture[] = [
  ...loadFixtures(fixturesDir('saber-stableswap')),
  ...loadFixtures(fixturesDir('meteora-damm-v1-stable')),
  ...loadFixtures(fixturesDir('raydium-cp-swap')),
];
const load = fixtureLoader(allFixtures);

const user = { outAta: 'user_out', inAta: 'user_in', owner: 'user_owner' };

function externalPool(quotedOut: bigint, label = 'prop-amm'): SolswapBestPool {
  const swap: VenueSwap = {
    programId: EXTERNAL_PROGRAM,
    data: new Uint8Array([9, 1, 1]),
    accounts: [
      { ref: user.inAta, writable: true },
      { ref: user.outAta, writable: true },
      { ref: EXTERNAL_POOL_STATE, address: EXTERNAL_POOL_STATE, writable: true },
    ],
  };
  return { external: { label, quotedOut, swap } };
}

function config(pools: SolswapBestPool[], overrides: Partial<SolswapBestConfig> = {}): SolswapBestConfig {
  return { amountIn: 1_000_000n, minOut: 1n, pools, user, load, ...overrides };
}

/** Occurrences of `needle` in `haystack`. */
function count(haystack: string, needle: string): number {
  return haystack.split(needle).length - 1;
}

/** Asserts each needle appears in `source`, in the given order, and returns their indices. */
function assertOrdered(source: string, needles: string[]): void {
  let from = -1;
  for (const needle of needles) {
    const at = source.indexOf(needle, from + 1);
    if (at <= from) {
      throw new Error(`expected '${needle}' after position ${from} in:\n${source}`);
    }
    from = at;
  }
}

describe('solswapBest stable helpers', () => {
  it('declares stableD/stableY exactly once for two stable pools of different venues', async () => {
    const { source } = await solswapBest(
      config([
        { venue: 'saber-stableswap', pool: SABER_POOL },
        { venue: 'meteora-damm-v1-stable', pool: METEORA_V1_POOL },
      ]),
    );

    expect(count(source, 'function stableD(')).toBe(1);
    expect(count(source, 'function stableY(')).toBe(1);
    // The helper block precedes main; both pool fragments call into it.
    expect(source.indexOf('function stableD(')).toBeLessThan(source.indexOf('function main()'));
    expect(count(source, 'stableD(')).toBeGreaterThanOrEqual(3); // 1 declaration + 2 call sites
    expect(count(source, 'stableY(')).toBeGreaterThanOrEqual(3);
  });

  it('omits the helpers when no stable pool is present', async () => {
    const { source } = await solswapBest(
      config([{ venue: 'raydium-cp-swap', pool: CP_POOL }, externalPool(500n)]),
    );

    expect(source).not.toContain('function stableD(');
    expect(source).not.toContain('function stableY(');
    expect(source.startsWith('function main()')).toBe(true);
  });
});

describe('solswapBest external quotes', () => {
  it('bakes the external quote as a constant candidate and reports it verbatim', async () => {
    const { source, quotes } = await solswapBest(
      config([{ venue: 'saber-stableswap', pool: SABER_POOL }, externalPool(123_456_789n, 'solfi')]),
    );

    expect(source).toContain('const q1 = 123456789;');
    expect(quotes).toHaveLength(2);
    expect(quotes[0].pool).toBe(SABER_POOL);
    expect(quotes[0].reference).toBeGreaterThan(0n);
    expect(quotes[1]).toEqual({ pool: 'solfi', reference: 123_456_789n });
  });

  it('interns each winner-candidate program account exactly once via a zero-length read', async () => {
    const { source } = await solswapBest(
      config([
        { venue: 'saber-stableswap', pool: SABER_POOL },
        externalPool(500n, 'prop-a'),
        externalPool(600n, 'prop-b'), // same program as prop-a — must dedupe
      ]),
    );

    expect(count(source, `accountData(${JSON.stringify(SABER_PROGRAM)}, 0, 0);`)).toBe(1);
    expect(count(source, `accountData(${JSON.stringify(EXTERNAL_PROGRAM)}, 0, 0);`)).toBe(1);
  });
});

describe('solswapBest scan and dispatch structure', () => {
  it('orders quotes, strictly-greater scan, pre-CPI minOut, baseline, dispatch, post-swap delta check', async () => {
    const { source, bytecode, accountPlan } = await solswapBest(
      config(
        [{ venue: 'saber-stableswap', pool: SABER_POOL }, externalPool(500n)],
        { minOut: 5n },
      ),
    );

    assertOrdered(source, [
      'const q1 = 500;', // quote fragments first
      'let bestOut = q0;', // scan seeds on the first-listed pool
      'let bestIndex = 0;',
      'if (q1 > bestOut) { bestOut = q1; bestIndex = 1 }', // strictly greater: ties keep the earlier pool
      'if (bestOut < 5) { throw "minOut" }', // inclusive bound, BEFORE any CPI
      'const before = accountUint("user_out", 64, 8);', // outAta baseline
      'if (bestIndex === 0) { contract.call(', // dispatch: one CPI to the winner
      'if (bestIndex === 1) { contract.call(',
      'const after = accountUint("user_out", 64, 8);',
      'const realized = after - before;',
      'if (realized < 5) { throw "out" }', // post-swap verification payload
      'return realized;', // the realized delta, not the predicted quote
    ]);

    // No dispatch arm precedes the minOut check.
    expect(source.indexOf('contract.call(')).toBeGreaterThan(source.indexOf('throw "minOut"'));

    expect(bytecode).toBeInstanceOf(Uint8Array);
    expect(bytecode.length).toBeGreaterThan(0);
    expect(accountPlan.metas.length).toBeGreaterThan(0);
  });

  it('stamps venue-resolved metas with their pubkeys and leaves user refs to the caller', async () => {
    const { accountPlan } = await solswapBest(
      config([{ venue: 'saber-stableswap', pool: SABER_POOL }, externalPool(500n)]),
    );

    const byRef = new Map(accountPlan.metas.map((meta) => [meta.ref, meta]));

    // Venue-resolved: the pool state account and both program accounts.
    expect(byRef.get(SABER_POOL)?.pubkey).toBe(SABER_POOL);
    expect(byRef.get(SABER_PROGRAM)?.pubkey).toBe(SABER_PROGRAM);
    expect(byRef.get(EXTERNAL_PROGRAM)?.pubkey).toBe(EXTERNAL_PROGRAM);
    expect(byRef.get(EXTERNAL_POOL_STATE)?.pubkey).toBe(EXTERNAL_POOL_STATE);

    // Caller-resolved: the user's refs carry no pubkey (and keep their flags).
    for (const ref of [user.outAta, user.inAta, user.owner]) {
      const meta = byRef.get(ref);
      expect(meta).toBeDefined();
      expect(meta?.pubkey).toBeUndefined();
    }
    expect(byRef.get(user.owner)?.signer).toBe(true);
  });

  it('surfaces the estimatePacket budget in warnings without duplicates', async () => {
    const output = await solswapBest(
      config([
        { venue: 'saber-stableswap', pool: SABER_POOL },
        { venue: 'meteora-damm-v1-stable', pool: METEORA_V1_POOL },
        { venue: 'raydium-cp-swap', pool: CP_POOL },
      ]),
    );

    const budget = estimatePacket(output.accountPlan, output.bytecode.length);
    for (const warning of budget.warnings) {
      expect(output.warnings).toContain(warning);
    }
    expect(new Set(output.warnings).size).toBe(output.warnings.length);
  });
});

describe('solswapBest validation', () => {
  it('rejects fewer than 2 or more than 8 pools', async () => {
    await expect(solswapBest(config([externalPool(1n)]))).rejects.toThrow('solswapBest expects 2 to 8 pools, got 1');
    const nine = Array.from({ length: 9 }, (_, i) => externalPool(BigInt(i + 1), `p${i}`));
    await expect(solswapBest(config(nine))).rejects.toThrow('solswapBest expects 2 to 8 pools, got 9');
  });

  it('rejects a non-positive amountIn and a negative minOut', async () => {
    const pools = [externalPool(1n, 'a'), externalPool(2n, 'b')];
    await expect(solswapBest(config(pools, { amountIn: 0n }))).rejects.toThrow(
      'solswapBest amountIn must be positive, got 0',
    );
    await expect(solswapBest(config(pools, { minOut: -1n }))).rejects.toThrow(
      'solswapBest minOut must be non-negative, got -1',
    );
  });

  it('rejects empty user refs', async () => {
    const pools = [externalPool(1n, 'a'), externalPool(2n, 'b')];
    await expect(solswapBest(config(pools, { user: { ...user, outAta: '' } }))).rejects.toThrow(
      'solswapBest user.outAta ref must not be empty',
    );
  });

  it('rejects malformed external entries', async () => {
    const ok = externalPool(2n, 'b');
    await expect(solswapBest(config([externalPool(1n, ''), ok]))).rejects.toThrow(
      'solswapBest external quote label must not be empty',
    );
    await expect(solswapBest(config([externalPool(0n, 'zero'), ok]))).rejects.toThrow(
      "solswapBest external quote 'zero' quotedOut must be positive, got 0",
    );
    const noAccounts = externalPool(1n, 'bare');
    (noAccounts as { external: { swap: VenueSwap } }).external.swap.accounts = [];
    await expect(solswapBest(config([noAccounts, ok]))).rejects.toThrow(
      "solswapBest external quote 'bare' swap.accounts must not be empty",
    );
  });

  it('rejects an unknown venue slug, listing the known venues', async () => {
    const pools: SolswapBestPool[] = [
      { venue: 'no-such-venue', pool: SABER_POOL },
      externalPool(1n),
    ];
    await expect(solswapBest(config(pools))).rejects.toThrow("unknown venue 'no-such-venue' (known venues: ");
  });
});
